// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.AcceptClaim;
using Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.AcceptOffer;
using Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.AcknowledgeReturnItem;
using Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.Adjudicate;
using Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.Appeal;
using Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.DenyOffer;
using Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.Escalate;
using Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.MakeOffer;
using Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.ProvideEvidence;
using Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.ProvideSupportingInfo;
using Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.RequireEvidence;
using Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.SendMessage;
using Soenneker.PayPal.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \customer_disputes_v1\v1\customer\disputes\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DisputesItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The acceptClaim property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.AcceptClaim.AcceptClaimRequestBuilder AcceptClaim
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.AcceptClaim.AcceptClaimRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The acceptOffer property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.AcceptOffer.AcceptOfferRequestBuilder AcceptOffer
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.AcceptOffer.AcceptOfferRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The acknowledgeReturnItem property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.AcknowledgeReturnItem.AcknowledgeReturnItemRequestBuilder AcknowledgeReturnItem
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.AcknowledgeReturnItem.AcknowledgeReturnItemRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The adjudicate property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.Adjudicate.AdjudicateRequestBuilder Adjudicate
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.Adjudicate.AdjudicateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The appeal property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.Appeal.AppealRequestBuilder Appeal
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.Appeal.AppealRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The denyOffer property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.DenyOffer.DenyOfferRequestBuilder DenyOffer
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.DenyOffer.DenyOfferRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The escalate property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.Escalate.EscalateRequestBuilder Escalate
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.Escalate.EscalateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The makeOffer property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.MakeOffer.MakeOfferRequestBuilder MakeOffer
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.MakeOffer.MakeOfferRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The provideEvidence property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.ProvideEvidence.ProvideEvidenceRequestBuilder ProvideEvidence
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.ProvideEvidence.ProvideEvidenceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The provideSupportingInfo property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.ProvideSupportingInfo.ProvideSupportingInfoRequestBuilder ProvideSupportingInfo
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.ProvideSupportingInfo.ProvideSupportingInfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The requireEvidence property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.RequireEvidence.RequireEvidenceRequestBuilder RequireEvidence
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.RequireEvidence.RequireEvidenceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sendMessage property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.SendMessage.SendMessageRequestBuilder SendMessage
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.SendMessage.SendMessageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.DisputesItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DisputesItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/customer_disputes_v1/v1/customer/disputes/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.DisputesItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DisputesItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/customer_disputes_v1/v1/customer/disputes/{id}", rawUrl)
        {
        }
        /// <summary>
        /// Shows details for a dispute, by ID.&lt;blockquote&gt;&lt;strong&gt;Note:&lt;/strong&gt; The fields that appear in the response depend on the access. For example, if the merchant requests shows dispute details, the customer&apos;s email ID does not appear.&lt;/blockquote&gt;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Dispute"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.PayPal.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.PayPal.OpenApiClient.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.PayPal.OpenApiClient.Models.Dispute?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.PayPal.OpenApiClient.Models.Dispute> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "500", global::Soenneker.PayPal.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "XXX", global::Soenneker.PayPal.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.PayPal.OpenApiClient.Models.Dispute>(requestInfo, global::Soenneker.PayPal.OpenApiClient.Models.Dispute.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Partially updates a dispute, by ID. Seller can update the `communication_detail` value or The partner can add the `partner action` information.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Subsequent_action"/></returns>
        /// <param name="body">An array of JSON patch objects to apply partial updates to resources.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.PayPal.OpenApiClient.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.PayPal.OpenApiClient.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.PayPal.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.PayPal.OpenApiClient.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.PayPal.OpenApiClient.Models.Subsequent_action?> PatchAsync(List<global::Soenneker.PayPal.OpenApiClient.Models.Customer_disputes_v1_patch> body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.PayPal.OpenApiClient.Models.Subsequent_action> PatchAsync(List<global::Soenneker.PayPal.OpenApiClient.Models.Customer_disputes_v1_patch> body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.PayPal.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.PayPal.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.PayPal.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "XXX", global::Soenneker.PayPal.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.PayPal.OpenApiClient.Models.Subsequent_action>(requestInfo, global::Soenneker.PayPal.OpenApiClient.Models.Subsequent_action.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Shows details for a dispute, by ID.&lt;blockquote&gt;&lt;strong&gt;Note:&lt;/strong&gt; The fields that appear in the response depend on the access. For example, if the merchant requests shows dispute details, the customer&apos;s email ID does not appear.&lt;/blockquote&gt;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Partially updates a dispute, by ID. Seller can update the `communication_detail` value or The partner can add the `partner action` information.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">An array of JSON patch objects to apply partial updates to resources.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(List<global::Soenneker.PayPal.OpenApiClient.Models.Customer_disputes_v1_patch> body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(List<global::Soenneker.PayPal.OpenApiClient.Models.Customer_disputes_v1_patch> body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.DisputesItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.DisputesItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.PayPal.OpenApiClient.Customer_disputes_v1.V1.Customer.Disputes.Item.DisputesItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
