{
  "openapi": "3.0.4",
  "info": {
    "title": "Merged OpenAPI",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://api-m.sandbox.paypal.com",
      "description": "PayPal Sandbox Environment"
    },
    {
      "url": "https://api-m.paypal.com",
      "description": "PayPal Live Environment"
    }
  ],
  "paths": {
    "/billing_subscriptions_v1/v1/billing/plans": {
      "post": {
        "tags": [
          "plans"
        ],
        "summary": "Create plan",
        "description": "Creates a plan that defines pricing and billing cycle details for subscriptions.",
        "operationId": "billing_subscriptions_v1_plans_create",
        "security": [
          {
            "Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "plans"
        ],
        "summary": "List plans",
        "description": "Lists billing plans.",
        "operationId": "billing_subscriptions_v1_plans_list",
        "security": [
          {
            "Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      }
    },
    "/billing_subscriptions_v1/v1/billing/plans/{id}": {
      "get": {
        "tags": [
          "plans"
        ],
        "summary": "Show plan details",
        "description": "Shows details for a plan, by ID.",
        "operationId": "billing_subscriptions_v1_plans_get",
        "security": [
          {
            "Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "plans"
        ],
        "summary": "Update plan",
        "description": "Updates a plan with the `CREATED` or `ACTIVE` status. For an `INACTIVE` plan, you can make only status updates.<br/>You can patch these attributes and objects:<table><thead><tr><th>Attribute or object</th><th>Operations</th></tr></thead><tbody><tr><td><code>description</code></td><td>replace</td></tr><tr><td><code>payment_preferences.auto_bill_outstanding</code></td><td>replace</td></tr><tr><td><code>taxes.percentage</code></td><td>replace</td></tr><tr><td><code>payment_p[...]",
        "operationId": "billing_subscriptions_v1_plans_patch",
        "security": [
          {
            "Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      }
    },
    "/billing_subscriptions_v1/v1/billing/plans/{id}/activate": {
      "post": {
        "tags": [
          "plans"
        ],
        "summary": "Activate plan",
        "description": "Activates a plan, by ID.",
        "operationId": "billing_subscriptions_v1_plans_activate",
        "security": [
          {
            "Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      }
    },
    "/billing_subscriptions_v1/v1/billing/plans/{id}/deactivate": {
      "post": {
        "tags": [
          "plans"
        ],
        "summary": "Deactivate plan",
        "description": "Deactivates a plan, by ID.",
        "operationId": "billing_subscriptions_v1_plans_deactivate",
        "security": [
          {
            "Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      }
    },
    "/billing_subscriptions_v1/v1/billing/plans/{id}/update-pricing-schemes": {
      "post": {
        "tags": [
          "plans"
        ],
        "summary": "Update pricing",
        "description": "Updates pricing for a plan. For example, you can update a regular billing cycle from $5 per month to $7 per month.",
        "operationId": "billing_subscriptions_v1_plans_update_pricing_schemes",
        "security": [
          {
            "Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      }
    },
    "/billing_subscriptions_v1/v1/billing/subscriptions": {
      "post": {
        "tags": [
          "subscriptions"
        ],
        "summary": "Create subscription",
        "description": "Creates a subscription.",
        "operationId": "billing_subscriptions_v1_subscriptions_create",
        "security": [
          {
            "Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      }
    },
    "/billing_subscriptions_v1/v1/billing/subscriptions/{id}": {
      "get": {
        "tags": [
          "subscriptions"
        ],
        "summary": "Show subscription details",
        "description": "Shows details for a subscription, by ID.",
        "operationId": "billing_subscriptions_v1_subscriptions_get",
        "security": [
          {
            "Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "subscriptions"
        ],
        "summary": "Update subscription",
        "description": "Updates a subscription which could be in <code>ACTIVE</code> or <code>SUSPENDED</code> status. You can override plan level default attributes by providing customised values for plan path in the patch request.<br /> <ul> <li>You cannot update attributes that have already completed (Example - trial cycles can’t be updated if completed).</li> <li>Once overridden, changes to plan resource will not impact subscription.</li> <li>Any price update will not impact billing cycles w[...]",
        "operationId": "billing_subscriptions_v1_subscriptions_patch",
        "security": [
          {
            "Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      }
    },
    "/billing_subscriptions_v1/v1/billing/subscriptions/{id}/revise": {
      "post": {
        "tags": [
          "subscriptions"
        ],
        "summary": "Revise plan or quantity of subscription",
        "description": "Updates the quantity of the product or service in a subscription. You can also use this method to switch the plan and update the `shipping_amount`, `shipping_address` values for the subscription. This type of update requires the buyer's consent.",
        "operationId": "billing_subscriptions_v1_subscriptions_revise",
        "security": [
          {
            "Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      }
    },
    "/billing_subscriptions_v1/v1/billing/subscriptions/{id}/suspend": {
      "post": {
        "tags": [
          "subscriptions"
        ],
        "summary": "Suspend subscription",
        "description": "Suspends the subscription.",
        "operationId": "billing_subscriptions_v1_subscriptions_suspend",
        "security": [
          {
            "Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      }
    },
    "/billing_subscriptions_v1/v1/billing/subscriptions/{id}/cancel": {
      "post": {
        "tags": [
          "subscriptions"
        ],
        "summary": "Cancel subscription",
        "description": "Cancels the subscription.",
        "operationId": "billing_subscriptions_v1_subscriptions_cancel",
        "security": [
          {
            "Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      }
    },
    "/billing_subscriptions_v1/v1/billing/subscriptions/{id}/activate": {
      "post": {
        "tags": [
          "subscriptions"
        ],
        "summary": "Activate subscription",
        "description": "Activates the subscription.",
        "operationId": "billing_subscriptions_v1_subscriptions_activate",
        "security": [
          {
            "Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      }
    },
    "/billing_subscriptions_v1/v1/billing/subscriptions/{id}/capture": {
      "post": {
        "tags": [
          "subscriptions"
        ],
        "summary": "Capture authorized payment on subscription",
        "description": "Captures an authorized payment from the subscriber on the subscription.",
        "operationId": "billing_subscriptions_v1_subscriptions_capture",
        "security": [
          {
            "Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      }
    },
    "/billing_subscriptions_v1/v1/billing/subscriptions/{id}/transactions": {
      "get": {
        "tags": [
          "subscriptions"
        ],
        "summary": "List transactions for subscription",
        "description": "Lists transactions for a subscription.",
        "operationId": "billing_subscriptions_v1_subscriptions_transactions",
        "security": [
          {
            "Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      }
    },
    "/catalogs_products_v1/v1/catalogs/products": {
      "post": {
        "tags": [
          "products"
        ],
        "summary": "Create product",
        "description": "Creates a product.",
        "operationId": "catalogs_products_v1_products_create",
        "security": [
          {
            "catalogs_products_v1_Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "products"
        ],
        "summary": "List products",
        "description": "Lists products.",
        "operationId": "catalogs_products_v1_products_list",
        "security": [
          {
            "catalogs_products_v1_Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      }
    },
    "/catalogs_products_v1/v1/catalogs/products/{product_id}": {
      "get": {
        "tags": [
          "products"
        ],
        "summary": "Show product details",
        "description": "Shows details for a product, by ID.",
        "operationId": "catalogs_products_v1_products_get",
        "security": [
          {
            "catalogs_products_v1_Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "products"
        ],
        "summary": "Update product",
        "description": "Updates a product, by ID. You can patch these attributes and objects:<table><thead><tr><th>Attribute or object</th><th>Operations</th></tr></thead><tbody><tr><td><code>description</code></td><td>add, replace, remove</td></tr><tr><td><code>category</code></td><td>add, replace, remove</td></tr><tr><td><code>image_url</code></td><td>add, replace, remove</td></tr><tr><td><code>home_url</code></td><td>add, replace, remove</td></tr></tbody></table>",
        "operationId": "catalogs_products_v1_products_patch",
        "security": [
          {
            "catalogs_products_v1_Oauth2": [
              "https://uri.paypal.com/services/subscriptions"
            ]
          }
        ]
      }
    },
    "/checkout_orders_v2/v2/checkout/orders": {
      "post": {
        "tags": [
          "orders"
        ],
        "summary": "Create order",
        "description": "Creates an order. Merchants and partners can add Level 2 and 3 data to payments to reduce risk and payment processing costs. For more information about processing payments, see <a href=\"https://developer.paypal.com/docs/checkout/advanced/processing/\">checkout</a> or <a href=\"https://developer.paypal.com/docs/multiparty/checkout/advanced/processing/\">multiparty checkout</a>.<blockquote><strong>Note:</strong> For error handling and troubleshooting, see <a href=\"https:/[...]",
        "operationId": "checkout_orders_v2_orders_create",
        "security": [
          {
            "checkout_orders_v2_Oauth2": [
              "https://uri.paypal.com/services/payments/payment",
              "https://uri.paypal.com/services/payments/orders/deprecating-jssdk-migration-for-limited-merchants"
            ]
          }
        ]
      }
    },
    "/checkout_orders_v2/v2/checkout/orders/{id}": {
      "get": {
        "tags": [
          "orders"
        ],
        "summary": "Show order details",
        "description": "Shows details for an order, by ID.<blockquote><strong>Note:</strong> For error handling and troubleshooting, see <a href=\"https://developer.paypal.com/api/rest/reference/orders/v2/errors/#get-order\">Orders v2 errors</a>.</blockquote>",
        "operationId": "checkout_orders_v2_orders_get",
        "security": [
          {
            "checkout_orders_v2_Oauth2": [
              "https://uri.paypal.com/services/payments/payment",
              "https://uri.paypal.com/services/payments/orders/deprecating-jssdk-migration-for-limited-merchants"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "orders"
        ],
        "summary": "Update order",
        "description": "Updates an order with a `CREATED` or `APPROVED` status. You cannot update an order with the `COMPLETED` status.<br/><br/>To make an update, you must provide a `reference_id`. If you omit this value with an order that contains only one purchase unit, PayPal sets the value to `default` which enables you to use the path: <code>\\\"/purchase_units/@reference_id=='default'/{attribute-or-object}\\\"</code>. Merchants and partners can add Level 2 and 3 data to payments to reduce[...]",
        "operationId": "checkout_orders_v2_orders_patch",
        "security": [
          {
            "checkout_orders_v2_Oauth2": [
              "https://uri.paypal.com/services/payments/payment",
              "https://uri.paypal.com/services/payments/orders/deprecating-jssdk-migration-for-limited-merchants"
            ]
          }
        ]
      }
    },
    "/checkout_orders_v2/v2/checkout/orders/{id}/confirm-payment-source": {
      "post": {
        "tags": [
          "orders"
        ],
        "summary": "Confirm the Order",
        "description": "Payer confirms their intent to pay for the the Order with the given payment source.",
        "operationId": "checkout_orders_v2_orders_confirm",
        "security": [
          {
            "checkout_orders_v2_Oauth2": [
              "https://uri.paypal.com/services/payments/payment",
              "https://uri.paypal.com/services/payments/initiatepayment",
              "https://uri.paypal.com/services/payments/orders/client_sdk_orders_api"
            ]
          }
        ]
      }
    },
    "/checkout_orders_v2/v2/checkout/orders/{id}/authorize": {
      "post": {
        "tags": [
          "orders"
        ],
        "summary": "Authorize payment for order",
        "description": "Authorizes payment for an order. To successfully authorize payment for an order, the buyer must first approve the order or a valid payment_source must be provided in the request. A buyer can approve the order upon being redirected to the rel:approve URL that was returned in the HATEOAS links in the create order response.<blockquote><strong>Note:</strong> For error handling and troubleshooting, see <a href=\"https://developer.paypal.com/api/rest/reference/orders/v2/errors/[...]",
        "operationId": "checkout_orders_v2_orders_authorize",
        "security": [
          {
            "checkout_orders_v2_Oauth2": [
              "https://uri.paypal.com/services/payments/payment",
              "https://uri.paypal.com/services/payments/orders/deprecating-jssdk-migration-for-limited-merchants"
            ]
          }
        ]
      }
    },
    "/checkout_orders_v2/v2/checkout/orders/{id}/capture": {
      "post": {
        "tags": [
          "orders"
        ],
        "summary": "Capture payment for order",
        "description": "Captures payment for an order. To successfully capture payment for an order, the buyer must first approve the order or a valid payment_source must be provided in the request. A buyer can approve the order upon being redirected to the rel:approve URL that was returned in the HATEOAS links in the create order response.<blockquote><strong>Note:</strong> For error handling and troubleshooting, see <a href=\"https://developer.paypal.com/api/rest/reference/orders/v2/errors/#cap[...]",
        "operationId": "checkout_orders_v2_orders_capture",
        "security": [
          {
            "checkout_orders_v2_Oauth2": [
              "https://uri.paypal.com/services/payments/payment",
              "https://uri.paypal.com/services/payments/orders/deprecating-jssdk-migration-for-limited-merchants"
            ]
          }
        ]
      }
    },
    "/checkout_orders_v2/v2/checkout/orders/{id}/track": {
      "post": {
        "tags": [
          "orders"
        ],
        "summary": "Add tracking information for an Order.",
        "description": "Adds tracking information for an Order.",
        "operationId": "checkout_orders_v2_orders_track_create",
        "security": [
          {
            "checkout_orders_v2_Oauth2": [
              "https://uri.paypal.com/services/payments/payment"
            ]
          }
        ]
      }
    },
    "/checkout_orders_v2/v2/checkout/orders/{id}/trackers/{tracker_id}": {
      "patch": {
        "tags": [
          "trackers"
        ],
        "summary": "Update or cancel tracking information for an order",
        "description": "Updates or cancels the tracking information for a PayPal order, by ID. Updatable attributes or objects:<br/><br/><table><thead><th>Attribute</th><th>Op</th><th>Notes</th></thead><tbody></tr><tr><td><code>items</code></td><td>replace</td><td>Using replace op for <code>items</code> will replace the entire <code>items</code> object with the value sent in request.</td></tr><tr><td><code>notify_payer</code></td><td>replace, add</td><td></td></tr><tr><td><code>status</code></td[...]",
        "operationId": "checkout_orders_v2_orders_trackers_patch",
        "security": [
          {
            "checkout_orders_v2_Oauth2": [
              "https://uri.paypal.com/services/payments/payment"
            ]
          }
        ]
      }
    },
    "/checkout_orders_v2/v2/checkout/orders/order-update-callback": {
      "post": {
        "tags": [
          "externalcallback"
        ],
        "summary": "Receive updated order information via callback URL",
        "description": "The documentation for this 'endpoint' is different from the other endpoints under v2 Orders. For this endpoint the role of client and server is reversed. The client sending the request is PayPal, and the server sending the response is the merchant. In the request, PayPal will send the buyer's redacted shipping address and selected shipping option to the callback URL defined the create order request. The response from the merchant will update the Orders resource.",
        "operationId": "checkout_orders_v2_server_callback"
      }
    },
    "/customer_disputes_v1/v1/customer/disputes": {
      "get": {
        "tags": [
          "disputes"
        ],
        "summary": "List disputes",
        "description": "Lists disputes with a summary set of details, which shows the <code>dispute_id</code>, <code>reason</code>, <code>status</code>, <code>dispute_state</code>, <code>dispute_life_cycle_stage</code>, <code>dispute_channel</code>, <code>dispute_amount</code>, <code>create_time</code> and <code>update_time</code> fields.<br/><br/>To filter the disputes in the response, specify one or more optional query parameters. To limit the number of disputes in the response, specify the <c[...]",
        "operationId": "customer_disputes_v1_disputes_list",
        "security": [
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/read-buyer"
            ]
          },
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/read-seller"
            ]
          },
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/read-ebay"
            ]
          },
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/read"
            ]
          },
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/read-partner"
            ]
          }
        ]
      }
    },
    "/customer_disputes_v1/v1/customer/disputes/{id}": {
      "get": {
        "tags": [
          "disputes"
        ],
        "summary": "Show dispute details",
        "description": "Shows details for a dispute, by ID.<blockquote><strong>Note:</strong> The fields that appear in the response depend on the access. For example, if the merchant requests shows dispute details, the customer's email ID does not appear.</blockquote>",
        "operationId": "customer_disputes_v1_disputes_get",
        "security": [
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/read-buyer"
            ]
          },
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/read-seller"
            ]
          },
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/read-ebay"
            ]
          },
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/read"
            ]
          },
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/read-partner"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "disputes"
        ],
        "summary": "Partially update dispute",
        "description": "Partially updates a dispute, by ID. Seller can update the `communication_detail` value or The partner can add the `partner action` information.",
        "operationId": "customer_disputes_v1_disputes_patch",
        "security": [
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-seller"
            ]
          }
        ]
      }
    },
    "/customer_disputes_v1/v1/customer/disputes/{id}/provide-evidence": {
      "post": {
        "tags": [
          "disputes-actions"
        ],
        "summary": "Provide evidence",
        "description": "Provides evidence for a dispute, by ID. A merchant can provide evidence for disputes with the <code>WAITING_FOR_SELLER_RESPONSE</code> status while customers can provide evidence for disputes with the <code>WAITING_FOR_BUYER_RESPONSE</code> status. Evidence can be a proof of delivery or proof of refund document or notes, which can include logs. A proof of delivery document includes a tracking number while a proof of refund document includes a refund ID. For other evidence[...]",
        "operationId": "customer_disputes_v1_disputes_provide_evidence",
        "security": [
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-seller"
            ]
          },
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-buyer"
            ]
          },
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-partner"
            ]
          }
        ]
      }
    },
    "/customer_disputes_v1/v1/customer/disputes/{id}/appeal": {
      "post": {
        "tags": [
          "disputes-actions"
        ],
        "summary": "Appeal dispute",
        "description": "Appeals a dispute, by ID. To appeal a dispute, use the <code>appeal</code> link in the <a href=\"/docs/api/reference/api-responses/#hateoas-links/\">HATEOAS links</a> from the show dispute details response. If this link does not appear, you cannot appeal the dispute. Submit new evidence as a document or notes in the JSON request body. For constraints and rules regarding documents, see <a href=\"/docs/integration/direct/customer-disputes/integration-guide/#documents\">docu[...]",
        "operationId": "customer_disputes_v1_disputes_appeal",
        "security": [
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-seller"
            ]
          },
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-buyer"
            ]
          }
        ]
      }
    },
    "/customer_disputes_v1/v1/customer/disputes/{id}/accept-claim": {
      "post": {
        "tags": [
          "disputes-actions"
        ],
        "summary": "Accept claim",
        "description": "Accepts liability for a claim, by ID. When you accept liability for a claim, the dispute closes in the customer’s favor and PayPal automatically refunds money to the customer from the merchant's account. Allowed accept_claim_type values for the request is available in dispute details <a href=\"/docs/api/customer-disputes/v1/#definition-allowed_response_options\">allowed response options</a> object.",
        "operationId": "customer_disputes_v1_disputes_accept_claim",
        "security": [
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-seller"
            ]
          }
        ]
      }
    },
    "/customer_disputes_v1/v1/customer/disputes/{id}/adjudicate": {
      "post": {
        "tags": [
          "disputes-actions"
        ],
        "summary": "Settle dispute",
        "description": "<blockquote><strong>Important:</strong> This method is for sandbox use only.</blockquote> Settles a dispute in either the customer's or merchant's favor. Merchants can make this call in the sandbox to complete end-to-end dispute resolution testing, which mimics the dispute resolution that PayPal agents normally complete. To make this call, the dispute <code>status</code> must be <code>UNDER_REVIEW</code> and <code>adjudicate</code> link  should be available in the <a href[...]",
        "operationId": "customer_disputes_v1_disputes_adjudicate",
        "security": [
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-seller"
            ]
          },
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-buyer"
            ]
          }
        ]
      }
    },
    "/customer_disputes_v1/v1/customer/disputes/{id}/require-evidence": {
      "post": {
        "tags": [
          "disputes-actions"
        ],
        "summary": "Update dispute status",
        "description": "<blockquote><strong>Important:</strong> This method is for sandbox use only.</blockquote> Updates the status of a dispute, by ID, from <code>UNDER_REVIEW</code> to either:<ul><li><code>WAITING_FOR_BUYER_RESPONSE</code></li><li><code>WAITING_FOR_SELLER_RESPONSE</code></li></ul>This status change enables either the customer or merchant to submit evidence for the dispute. To make this call, the dispute <code>status</code> must be <code>UNDER_REVIEW</code> and <code>require-e[...]",
        "operationId": "customer_disputes_v1_disputes_require_evidence",
        "security": [
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-seller"
            ]
          },
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-buyer"
            ]
          }
        ]
      }
    },
    "/customer_disputes_v1/v1/customer/disputes/{id}/escalate": {
      "post": {
        "tags": [
          "disputes-actions"
        ],
        "summary": "Escalate dispute to claim",
        "description": "Escalates the dispute, by ID, to a PayPal claim. To make this call, the stage in the dispute lifecycle must be `INQUIRY`.",
        "operationId": "customer_disputes_v1_disputes_escalate",
        "security": [
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-seller"
            ]
          },
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-buyer"
            ]
          }
        ]
      }
    },
    "/customer_disputes_v1/v1/customer/disputes/{id}/send-message": {
      "post": {
        "tags": [
          "disputes-actions"
        ],
        "summary": "Send message about dispute to other party",
        "description": "Sends a message about a dispute, by ID, to the other party in the dispute. Merchants and customers can only send messages if the `dispute_life_cycle_stage` value is `INQUIRY`. For constraints and rules regarding documents that can be attached as part of the message, see <a href=\"/docs/integration/direct/customer-disputes/integration-guide/#documents\">documents</a>. To send a message, use the <code>send-message</code> link in the <a href=\"/docs/api/reference/api-respons[...]",
        "operationId": "customer_disputes_v1_disputes_send_message",
        "security": [
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-seller"
            ]
          },
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-buyer"
            ]
          }
        ]
      }
    },
    "/customer_disputes_v1/v1/customer/disputes/{id}/make-offer": {
      "post": {
        "tags": [
          "disputes-actions"
        ],
        "summary": "Make offer to resolve dispute",
        "description": "Makes an offer to the other party to resolve a dispute, by ID. To make this call, the stage in the dispute lifecycle must be `INQUIRY`. If the customer accepts the offer, PayPal automatically makes a refund. Allowed offer_type values for the request is available in dispute details <a href=\"/docs/api/customer-disputes/v1/#definition-allowed_response_options\">allowed response options</a> object.",
        "operationId": "customer_disputes_v1_disputes_make_offer",
        "security": [
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-seller"
            ]
          },
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-buyer"
            ]
          }
        ]
      }
    },
    "/customer_disputes_v1/v1/customer/disputes/{id}/accept-offer": {
      "post": {
        "tags": [
          "disputes-actions"
        ],
        "summary": "Accept offer to resolve dispute",
        "description": "The customer accepts the offer from merchant to resolve a dispute, by ID. PayPal automatically refunds the amount proposed by merchant to the customer.",
        "operationId": "customer_disputes_v1_disputes_accept_offer",
        "security": [
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-buyer"
            ]
          }
        ]
      }
    },
    "/customer_disputes_v1/v1/customer/disputes/{id}/deny-offer": {
      "post": {
        "tags": [
          "disputes-actions"
        ],
        "summary": "Deny offer to resolve dispute",
        "description": "Denies an offer that the merchant proposes for a dispute, by ID.",
        "operationId": "customer_disputes_v1_disputes_deny_offer",
        "security": [
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-buyer"
            ]
          }
        ]
      }
    },
    "/customer_disputes_v1/v1/customer/disputes/{id}/acknowledge-return-item": {
      "post": {
        "tags": [
          "disputes-actions"
        ],
        "summary": "Acknowledge returned item",
        "description": "Acknowledges that the customer returned an item for a dispute, by ID. A merchant can make this request for disputes with the `MERCHANDISE_OR_SERVICE_NOT_AS_DESCRIBED` reason. Allowed acknowledgement_type values for the request is available in dispute details <a href=\"/docs/api/customer-disputes/v1/#definition-allowed_response_options\">allowed response options</a> object. For constraints and rules regarding documents, see <a href=\"/docs/integration/direct/customer-dispu[...]",
        "operationId": "customer_disputes_v1_disputes_acknowledge_return_item",
        "security": [
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-seller"
            ]
          }
        ]
      }
    },
    "/customer_disputes_v1/v1/customer/disputes/{id}/provide-supporting-info": {
      "post": {
        "tags": [
          "disputes-actions"
        ],
        "summary": "Provide supporting information for dispute",
        "description": "Provides supporting information for a dispute, by ID. A merchant or buyer can make this request for disputes if they find the `provide-supporting-info` link in the HATEOAS links in the list disputes response. The party can provide the supporting information to PayPal to defend themselves only when the `dispute_life_cycle_stage` is `CHARGEBACK`, `PRE_ARBITRATION`, or `ARBITRATION`. They can provide a note that describes their part with details or upload any supporting docu[...]",
        "operationId": "customer_disputes_v1_disputes_provide_supporting_info",
        "security": [
          {
            "customer_disputes_v1_Oauth2": [
              "https://uri.paypal.com/services/disputes/update-seller",
              "https://uri.paypal.com/services/disputes/update-buyer",
              "https://uri.paypal.com/services/disputes/update-partner"
            ]
          }
        ]
      }
    },
    "/customer_partner_referrals_v2/v2/customer/partner-referrals": {
      "post": {
        "tags": [
          "partner-referrals"
        ],
        "summary": "Create partner referral",
        "description": "Creates a partner referral that is shared by the partner or API caller. The partner referral is used to onboard the seller, and contains the seller's personal, business, financial and operations.",
        "operationId": "customer_partner_referrals_v2_partner_referrals_create",
        "security": [
          {
            "customer_partner_referrals_v2_Oauth2": [
              "https://uri.paypal.com/services/customer/partner-referrals/readwrite"
            ]
          }
        ]
      }
    },
    "/customer_partner_referrals_v2/v2/customer/partner-referrals/{partner_referral_id}": {
      "get": {
        "tags": [
          "partner-referrals"
        ],
        "summary": "Show referral data",
        "description": "Shows details by ID for referral data that was shared by the partner or API caller.",
        "operationId": "customer_partner_referrals_v2_partner_referrals_read",
        "security": [
          {
            "customer_partner_referrals_v2_Oauth2": [
              "https://uri.paypal.com/services/customer/partner-referrals/readwrite"
            ]
          },
          {
            "customer_partner_referrals_v2_Oauth2": [
              "https://uri.paypal.com/services/customer/partner-referrals"
            ]
          }
        ]
      }
    },
    "/invoicing_v2/v2/invoicing/invoices": {
      "post": {
        "tags": [
          "invoices"
        ],
        "summary": "Create draft invoice",
        "description": "Creates a draft invoice. To move the invoice from a draft to payable state, you must <a href=\"#invoices_send\">send the invoice</a>.<br/><br/>In the JSON request body, include invoice details including merchant information. The <code>invoice</code> object must include an <code>items</code> array.<blockquote><strong>Note:</strong> The merchant that you specify in an invoice must have a PayPal account in good standing.</blockquote>.",
        "operationId": "invoicing_v2_invoices_create",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/readwrite"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "invoices"
        ],
        "summary": "List invoices",
        "description": "Lists invoices. To filter the invoices that appear in the response, you can specify one or more optional query parameters.",
        "operationId": "invoicing_v2_invoices_list",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/read"
            ]
          }
        ]
      }
    },
    "/invoicing_v2/v2/invoicing/invoices/{invoice_id}/send": {
      "post": {
        "tags": [
          "invoices"
        ],
        "summary": "Send invoice",
        "description": "Sends or schedules an invoice, by ID, to be sent to a customer. The action depends on the invoice issue date:<ul><li>If the invoice issue date is current or in the past, sends the invoice immediately.</li><li>If the invoice issue date is in the future, schedules the invoice to be sent on that date.</li></ul>To suppress the merchant's email notification, set the `send_to_invoicer` body parameter to `false`. To send the invoice through a share link and not through PayPal, s[...]",
        "operationId": "invoicing_v2_invoices_send",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/readwrite"
            ]
          }
        ]
      }
    },
    "/invoicing_v2/v2/invoicing/invoices/{invoice_id}/remind": {
      "post": {
        "tags": [
          "invoices"
        ],
        "summary": "Send invoice reminder",
        "description": "Sends a reminder to the payer about an invoice, by ID. In the JSON request body, include a `notification` object that defines the subject of the reminder and other details. <blockquote><strong>Notes:</strong><ul><li>API caller can send only 2 reminders in a day.</li></ul></blockquote>.",
        "operationId": "invoicing_v2_invoices_remind",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/readwrite"
            ]
          }
        ]
      }
    },
    "/invoicing_v2/v2/invoicing/invoices/{invoice_id}/cancel": {
      "post": {
        "tags": [
          "invoices"
        ],
        "summary": "Cancel sent invoice",
        "description": "Cancels a sent invoice, by ID, and, optionally, sends a notification about the cancellation to the payer, merchant, and CC: emails.",
        "operationId": "invoicing_v2_invoices_cancel",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/readwrite"
            ]
          }
        ]
      }
    },
    "/invoicing_v2/v2/invoicing/invoices/{invoice_id}/payments": {
      "post": {
        "tags": [
          "invoices"
        ],
        "summary": "Record payment for invoice",
        "description": "Records a payment for the invoice. If no payment is due, the invoice is marked as `PAID`. Otherwise, the invoice is marked as `PARTIALLY PAID`.",
        "operationId": "invoicing_v2_invoices_payments",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/readwrite"
            ]
          }
        ]
      }
    },
    "/invoicing_v2/v2/invoicing/invoices/{invoice_id}/payments/{transaction_id}": {
      "delete": {
        "tags": [
          "invoices"
        ],
        "summary": "Delete external payment",
        "description": "Deletes an external payment, by invoice ID and transaction ID.",
        "operationId": "invoicing_v2_invoices_payments_delete",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/readwrite"
            ]
          }
        ]
      }
    },
    "/invoicing_v2/v2/invoicing/invoices/{invoice_id}/refunds": {
      "post": {
        "tags": [
          "invoices"
        ],
        "summary": "Record refund for invoice",
        "description": "Records a refund for the invoice. If all payments are refunded, the invoice is marked as `REFUNDED`. Otherwise, the invoice is marked as `PARTIALLY REFUNDED`.",
        "operationId": "invoicing_v2_invoices_refunds",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/readwrite"
            ]
          }
        ]
      }
    },
    "/invoicing_v2/v2/invoicing/invoices/{invoice_id}/refunds/{transaction_id}": {
      "delete": {
        "tags": [
          "invoices"
        ],
        "summary": "Delete external refund",
        "description": "Deletes an external refund, by invoice ID and transaction ID.",
        "operationId": "invoicing_v2_invoices_refunds_delete",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/readwrite"
            ]
          }
        ]
      }
    },
    "/invoicing_v2/v2/invoicing/invoices/{invoice_id}/generate-qr-code": {
      "post": {
        "tags": [
          "invoices"
        ],
        "summary": "Generate QR code",
        "description": "Generates a QR code for an invoice, by ID. The QR code is a PNG image in <a href=\"https://www.base64encode.org/\">Base64-encoded</a> format that corresponds to the invoice ID. You can generate a QR code for an invoice and add it to a paper or PDF invoice. When customers use their mobile devices to scan the QR code, they are redirected to the PayPal mobile payment flow where they can view the invoice and pay online with PayPal or a credit card. Before you get a QR code, y[...]",
        "operationId": "invoicing_v2_invoices_generate_qr_code",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/readwrite"
            ]
          }
        ]
      }
    },
    "/invoicing_v2/v2/invoicing/generate-next-invoice-number": {
      "post": {
        "tags": [
          "invoices"
        ],
        "summary": "Generate invoice number",
        "description": "Generates the next invoice number that is available to the merchant. The next invoice number uses the prefix and suffix from the last invoice number and increments the number by one. For example, the next invoice number after `INVOICE-1234` is `INVOICE-1235`.",
        "operationId": "invoicing_v2_invoicing_generate_next_invoice_number",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/readwrite"
            ]
          }
        ]
      }
    },
    "/invoicing_v2/v2/invoicing/invoices/{invoice_id}": {
      "get": {
        "tags": [
          "invoices"
        ],
        "summary": "Show invoice details",
        "description": "Shows details for an invoice, by ID.",
        "operationId": "invoicing_v2_invoices_get",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "invoices"
        ],
        "summary": "Fully update invoice",
        "description": "Fully updates an invoice, by ID. In the JSON request body, include a complete `invoice` object. This call does not support partial updates. <blockquote><strong>Notes:</strong><ul><li>API caller can change/modify recipient only 2 times in 72 hours.</li></ul></blockquote>.",
        "operationId": "invoicing_v2_invoices_update",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/readwrite"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "invoices"
        ],
        "summary": "Delete invoice",
        "description": "Deletes a draft or scheduled invoice, by ID. Deletes invoices in the draft or scheduled state only. For invoices that have already been sent, you can <a href=\"/docs/api/invoicing/v2/#invoices_cancel\">cancel the invoice</a>. After you delete a draft or scheduled invoice, you can no longer use it or show its details. However, you can reuse its invoice number.",
        "operationId": "invoicing_v2_invoices_delete",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/readwrite"
            ]
          }
        ]
      }
    },
    "/invoicing_v2/v2/invoicing/search-invoices": {
      "post": {
        "tags": [
          "search-invoices"
        ],
        "summary": "Search for invoices",
        "description": "Searches for and lists invoices that match search criteria. If you pass multiple criteria, the response lists invoices that match all criteria.",
        "operationId": "invoicing_v2_invoices_search_invoices",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/read"
            ]
          }
        ]
      }
    },
    "/invoicing_v2/v2/invoicing/templates": {
      "get": {
        "tags": [
          "templates"
        ],
        "summary": "List templates",
        "description": "Lists merchant-created templates with associated details. The associated details include the emails, addresses, and phone numbers from the user's PayPal profile.<br/>The user can select which values to show in the business information section of their template.",
        "operationId": "invoicing_v2_templates_list",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "templates"
        ],
        "summary": "Create template",
        "description": "Creates an invoice template. You can use details from this template to create an invoice. You can create up to 50 templates.<blockquote><strong>Note:</strong> Every merchant starts with three PayPal system templates that are optimized for the unit type billed. The template includes `Quantity`, `Hours`, and `Amount`.</blockquote>",
        "operationId": "invoicing_v2_templates_create",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/readwrite"
            ]
          }
        ]
      }
    },
    "/invoicing_v2/v2/invoicing/templates/{template_id}": {
      "get": {
        "tags": [
          "templates"
        ],
        "summary": "Show template details",
        "description": "Shows details for a template, by ID.",
        "operationId": "invoicing_v2_templates_get",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "templates"
        ],
        "summary": "Fully update template",
        "description": "Fully updates a template, by ID. In the JSON request body, include a complete `template` object. This call does not support partial updates.",
        "operationId": "invoicing_v2_templates_update",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/readwrite"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "templates"
        ],
        "summary": "Delete template",
        "description": "Deletes a template, by ID.",
        "operationId": "invoicing_v2_templates_delete",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/readwrite"
            ]
          }
        ]
      }
    },
    "/invoicing_v2/v2/invoicing/accounting-sync/merchant/connections": {
      "get": {
        "tags": [
          "connections"
        ],
        "summary": "List Connections.",
        "description": "Lists connections to accounting platforms per merchant.",
        "operationId": "invoicing_v2_connections_get",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/read",
              "https://uri.paypal.com/services/invoicing/invoices/readwrite",
              "https://uri.paypal.com/services/invoicing/internal"
            ]
          }
        ]
      }
    },
    "/invoicing_v2/v2/invoicing/accounting-sync/invoices/{id}/connections": {
      "get": {
        "tags": [
          "invoice-connection-details"
        ],
        "summary": "List Connection Status for an Invoice.",
        "description": "Lists connections to accounting platforms per invoice.",
        "operationId": "invoicing_v2_invoice_connection_details_get",
        "security": [
          {
            "invoicing_v2_Oauth2": [
              "https://uri.paypal.com/services/invoicing/invoices/read",
              "https://uri.paypal.com/services/invoicing/invoices/readwrite",
              "https://uri.paypal.com/services/invoicing/internal"
            ]
          }
        ]
      }
    },
    "/notifications_webhooks_v1/v1/notifications/webhooks": {
      "post": {
        "tags": [
          "webhooks"
        ],
        "summary": "Create webhook",
        "description": "Subscribes your webhook listener to events.",
        "operationId": "notifications_webhooks_v1_webhooks_post",
        "security": [
          {
            "notifications_webhooks_v1_Oauth2": [
              "https://uri.paypal.com/services/applications/webhooks"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "webhooks"
        ],
        "summary": "List webhooks",
        "description": "Lists webhooks for an app.",
        "operationId": "notifications_webhooks_v1_webhooks_list",
        "security": [
          {
            "notifications_webhooks_v1_Oauth2": [
              "https://uri.paypal.com/services/applications/webhooks"
            ]
          }
        ]
      }
    },
    "/notifications_webhooks_v1/v1/notifications/webhooks/{webhook_id}": {
      "get": {
        "tags": [
          "webhooks"
        ],
        "summary": "Show webhook details",
        "description": "Shows details for a webhook, by ID.",
        "operationId": "notifications_webhooks_v1_webhooks_get",
        "security": [
          {
            "notifications_webhooks_v1_Oauth2": [
              "https://uri.paypal.com/services/applications/webhooks"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "webhooks"
        ],
        "summary": "Update webhook",
        "description": "Updates a webhook to replace webhook fields with new values. Supports only the `replace` operation. Pass a `json_patch` object with `replace` operation and `path`, which is `/url` for a URL or `/event_types` for events. The `value` is either the URL or a list of events.",
        "operationId": "notifications_webhooks_v1_webhooks_update",
        "security": [
          {
            "notifications_webhooks_v1_Oauth2": [
              "https://uri.paypal.com/services/applications/webhooks"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "webhooks"
        ],
        "summary": "Delete webhook",
        "description": "Deletes a webhook, by ID.",
        "operationId": "notifications_webhooks_v1_webhooks_delete",
        "security": [
          {
            "notifications_webhooks_v1_Oauth2": [
              "https://uri.paypal.com/services/applications/webhooks"
            ]
          }
        ]
      }
    },
    "/notifications_webhooks_v1/v1/notifications/webhooks/{webhook_id}/event-types": {
      "get": {
        "tags": [
          "webhooks"
        ],
        "summary": "List event subscriptions for webhook",
        "description": "Lists event subscriptions for a webhook, by ID.",
        "operationId": "notifications_webhooks_v1_event_types_list",
        "security": [
          {
            "notifications_webhooks_v1_Oauth2": [
              "https://uri.paypal.com/services/applications/webhooks"
            ]
          }
        ]
      }
    },
    "/notifications_webhooks_v1/v1/notifications/webhooks-lookup": {
      "post": {
        "tags": [
          "webhooks-lookup"
        ],
        "summary": "Create webhook lookup",
        "description": "Creates a webhook lookup. A webhook lookup ties the API caller's REST API app to the subject account (or, if no subject is specified, to the API caller's account). If a webhook event is generated for an event that is tied to the account but not to a particular REST API app (for example, payments initiated with the NVP/SOAP APIs or through the user interface on PayPal.com), those webhook events will treated as if they were intended for the REST API app registered in the we[...]",
        "operationId": "notifications_webhooks_v1_webhooks_lookup_post",
        "security": [
          {
            "notifications_webhooks_v1_Oauth2": [
              "https://uri.paypal.com/services/applications/webhooks"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "webhooks-lookup"
        ],
        "summary": "List webhook lookups",
        "description": "Lists webhook lookups.",
        "operationId": "notifications_webhooks_v1_webhooks_lookup_list",
        "security": [
          {
            "notifications_webhooks_v1_Oauth2": [
              "https://uri.paypal.com/services/applications/webhooks"
            ]
          }
        ]
      }
    },
    "/notifications_webhooks_v1/v1/notifications/webhooks-lookup/{webhook_lookup_id}": {
      "get": {
        "tags": [
          "webhooks-lookup"
        ],
        "summary": "Show webhook lookup details",
        "description": "Shows details for a webhook lookup, by ID.",
        "operationId": "notifications_webhooks_v1_webhooks_lookup_get",
        "security": [
          {
            "notifications_webhooks_v1_Oauth2": [
              "https://uri.paypal.com/services/applications/webhooks"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "webhooks-lookup"
        ],
        "summary": "Delete webhook lookup",
        "description": "Deletes a webhook lookup, by ID.",
        "operationId": "notifications_webhooks_v1_webhooks_lookup_delete",
        "security": [
          {
            "notifications_webhooks_v1_Oauth2": [
              "https://uri.paypal.com/services/applications/webhooks"
            ]
          }
        ]
      }
    },
    "/notifications_webhooks_v1/v1/notifications/verify-webhook-signature": {
      "post": {
        "tags": [
          "verify-webhook-signature"
        ],
        "summary": "Verify webhook signature",
        "description": "Verifies a webhook signature.",
        "operationId": "notifications_webhooks_v1_verify_webhook_signature_post",
        "security": [
          {
            "notifications_webhooks_v1_Oauth2": [
              "https://uri.paypal.com/services/applications/webhooks",
              "https://uri.paypal.com/services/applications/verify-webhook-signature"
            ]
          }
        ]
      }
    },
    "/notifications_webhooks_v1/v1/notifications/webhooks-event-types": {
      "get": {
        "tags": [
          "webhooks-event-types"
        ],
        "summary": "List available events",
        "description": "Lists available events to which any webhook can subscribe. For a list of supported events, see [Webhook event names](/docs/api/notifications/webhooks/event-names/).",
        "operationId": "notifications_webhooks_v1_webhooks_event_types_list"
      }
    },
    "/notifications_webhooks_v1/v1/notifications/webhooks-events": {
      "get": {
        "tags": [
          "webhooks-events"
        ],
        "summary": "List event notifications",
        "description": "Lists webhooks event notifications. Use query parameters to filter the response.",
        "operationId": "notifications_webhooks_v1_webhooks_events_list",
        "security": [
          {
            "notifications_webhooks_v1_Oauth2": [
              "https://uri.paypal.com/services/applications/webhooks"
            ]
          }
        ]
      }
    },
    "/notifications_webhooks_v1/v1/notifications/webhooks-events/{event_id}": {
      "get": {
        "tags": [
          "webhooks-events"
        ],
        "summary": "Show event notification details",
        "description": "Shows details for a webhooks event notification, by ID.",
        "operationId": "notifications_webhooks_v1_webhooks_events_get",
        "security": [
          {
            "notifications_webhooks_v1_Oauth2": [
              "https://uri.paypal.com/services/applications/webhooks"
            ]
          }
        ]
      }
    },
    "/notifications_webhooks_v1/v1/notifications/webhooks-events/{event_id}/resend": {
      "post": {
        "tags": [
          "webhooks-events"
        ],
        "summary": "Resend event notification",
        "description": "Resends a webhook event notification, by ID. Any pending notifications are not resent.",
        "operationId": "notifications_webhooks_v1_webhooks_events_resend",
        "security": [
          {
            "notifications_webhooks_v1_Oauth2": [
              "https://uri.paypal.com/services/applications/webhooks"
            ]
          }
        ]
      }
    },
    "/notifications_webhooks_v1/v1/notifications/simulate-event": {
      "post": {
        "tags": [
          "simulate-event"
        ],
        "summary": "Simulate webhook event",
        "description": "Simulates a webhook event. In the JSON request body, specify a sample payload.<br>You need to subscribe to the following webhook events for Pay upon Invoice:<br><table><thead><tr><th>Event</th><th>Trigger</th></tr></thead><tbody><tr><td><code>PAYMENT.CAPTURE.COMPLETED</code></td><td>A payment capture completes.</td></tr><tr><td><code>PAYMENT.CAPTURE.DENIED</code></td><td>A payment capture is denied.</td></tr><tr><td><code>CHECKOUT.PAYMENT-APPROVAL.REVERSED</code></td><td>[...]",
        "operationId": "notifications_webhooks_v1_simulate_event_post",
        "security": [
          {
            "notifications_webhooks_v1_Oauth2": [
              "https://uri.paypal.com/services/applications/webhooks"
            ]
          }
        ]
      }
    },
    "/payment-experience_web_experience_profiles_v1/v1/payment-experience/web-profiles": {
      "post": {
        "tags": [
          "web-profiles"
        ],
        "summary": "Create web experience profile",
        "description": "Creates a web experience profile. In the JSON request body, specify the profile name and details.",
        "operationId": "payment_experience_web_experience_profiles_v1_web_profile_create",
        "security": [
          {
            "payment_experience_web_experience_profiles_v1_Oauth2": [
              "https://uri.paypal.com/services/payments/payment"
            ]
          },
          {
            "payment_experience_web_experience_profiles_v1_Oauth2": [
              "https://uri.paypal.com/services/payments/realtimepayment"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "web-profiles"
        ],
        "summary": "List web experience profiles",
        "description": "Lists the latest 20 web experience profiles for a merchant or subject. To show details for these or additional profiles, you can show web experience profile details by ID.",
        "operationId": "payment_experience_web_experience_profiles_v1_web_profile_get_list",
        "security": [
          {
            "payment_experience_web_experience_profiles_v1_Oauth2": [
              "https://uri.paypal.com/services/payments/payment"
            ]
          },
          {
            "payment_experience_web_experience_profiles_v1_Oauth2": [
              "https://uri.paypal.com/services/payments/realtimepayment"
            ]
          }
        ]
      }
    },
    "/payment-experience_web_experience_profiles_v1/v1/payment-experience/web-profiles/{id}": {
      "put": {
        "tags": [
          "web-profiles"
        ],
        "summary": "Update web experience profile",
        "description": "Updates a web experience profile, by ID. In the JSON request body, specify the profile details. If your request omits any profile parameters, any previously set values for those parameters are removed.",
        "operationId": "payment_experience_web_experience_profiles_v1_web_profile_update",
        "security": [
          {
            "payment_experience_web_experience_profiles_v1_Oauth2": [
              "https://uri.paypal.com/services/payments/payment"
            ]
          },
          {
            "payment_experience_web_experience_profiles_v1_Oauth2": [
              "https://uri.paypal.com/services/payments/realtimepayment"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "web-profiles"
        ],
        "summary": "Partially update web experience profile",
        "description": "Partially-updates a web experience profile, by ID. In the JSON request body, specify a patch object, the path of the profile location to update, and a new value.",
        "operationId": "payment_experience_web_experience_profiles_v1_web_profile_partial_update",
        "security": [
          {
            "payment_experience_web_experience_profiles_v1_Oauth2": [
              "https://uri.paypal.com/services/payments/payment"
            ]
          },
          {
            "payment_experience_web_experience_profiles_v1_Oauth2": [
              "https://uri.paypal.com/services/payments/realtimepayment"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "web-profiles"
        ],
        "summary": "Show web experience profile details by ID",
        "description": "Shows details for a web experience profile, by ID.",
        "operationId": "payment_experience_web_experience_profiles_v1_web_profile_get",
        "security": [
          {
            "payment_experience_web_experience_profiles_v1_Oauth2": [
              "https://uri.paypal.com/services/payments/payment"
            ]
          },
          {
            "payment_experience_web_experience_profiles_v1_Oauth2": [
              "https://uri.paypal.com/services/payments/realtimepayment"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "web-profiles"
        ],
        "summary": "Delete web experience profile",
        "description": "Deletes a web experience profile, by ID.",
        "operationId": "payment_experience_web_experience_profiles_v1_web_profile_delete",
        "security": [
          {
            "payment_experience_web_experience_profiles_v1_Oauth2": [
              "https://uri.paypal.com/services/payments/payment"
            ]
          },
          {
            "payment_experience_web_experience_profiles_v1_Oauth2": [
              "https://uri.paypal.com/services/payments/realtimepayment"
            ]
          }
        ]
      }
    },
    "/payments_payment_v2/v2/payments/authorizations/{authorization_id}": {
      "get": {
        "tags": [
          "authorizations"
        ],
        "summary": "Show details for authorized payment",
        "description": "Shows details for an authorized payment, by ID.",
        "operationId": "payments_payment_v2_authorizations_get",
        "security": [
          {
            "payments_payment_v2_Oauth2": [
              "https://uri.paypal.com/services/payments/payment/authcapture"
            ]
          }
        ]
      }
    },
    "/payments_payment_v2/v2/payments/authorizations/{authorization_id}/capture": {
      "post": {
        "tags": [
          "authorizations"
        ],
        "summary": "Capture authorized payment",
        "description": "Captures an authorized payment, by ID.",
        "operationId": "payments_payment_v2_authorizations_capture",
        "security": [
          {
            "payments_payment_v2_Oauth2": [
              "https://uri.paypal.com/services/payments/payment/authcapture"
            ]
          }
        ]
      }
    },
    "/payments_payment_v2/v2/payments/authorizations/{authorization_id}/reauthorize": {
      "post": {
        "tags": [
          "authorizations"
        ],
        "summary": "Reauthorize authorized payment",
        "description": "Reauthorizes an authorized PayPal account payment, by ID. To ensure that funds are still available, reauthorize a payment after its initial three-day honor period expires. Within the 29-day authorization period, you can issue multiple re-authorizations after the honor period expires.<br/><br/>If 30 days have transpired since the date of the original authorization, you must create an authorized payment instead of reauthorizing the original authorized payment.<br/><br/>A re[...]",
        "operationId": "payments_payment_v2_authorizations_reauthorize",
        "security": [
          {
            "payments_payment_v2_Oauth2": [
              "https://uri.paypal.com/services/payments/payment/authcapture"
            ]
          }
        ]
      }
    },
    "/payments_payment_v2/v2/payments/authorizations/{authorization_id}/void": {
      "post": {
        "tags": [
          "authorizations"
        ],
        "summary": "Void authorized payment",
        "description": "Voids, or cancels, an authorized payment, by ID. You cannot void an authorized payment that has been fully captured.",
        "operationId": "payments_payment_v2_authorizations_void",
        "security": [
          {
            "payments_payment_v2_Oauth2": [
              "https://uri.paypal.com/services/payments/payment/authcapture"
            ]
          }
        ]
      }
    },
    "/payments_payment_v2/v2/payments/captures/{capture_id}": {
      "get": {
        "tags": [
          "captures"
        ],
        "summary": "Show captured payment details",
        "description": "Shows details for a captured payment, by ID.",
        "operationId": "payments_payment_v2_captures_get",
        "security": [
          {
            "payments_payment_v2_Oauth2": [
              "https://uri.paypal.com/services/payments/payment/authcapture"
            ]
          }
        ]
      }
    },
    "/payments_payment_v2/v2/payments/captures/{capture_id}/refund": {
      "post": {
        "tags": [
          "captures"
        ],
        "summary": "Refund captured payment",
        "description": "Refunds a captured payment, by ID. For a full refund, include an empty payload in the JSON request body. For a partial refund, include an <code>amount</code> object in the JSON request body.",
        "operationId": "payments_payment_v2_captures_refund",
        "security": [
          {
            "payments_payment_v2_Oauth2": [
              "https://uri.paypal.com/services/payments/refund"
            ]
          }
        ]
      }
    },
    "/payments_payment_v2/v2/payments/refunds/{refund_id}": {
      "get": {
        "tags": [
          "refunds"
        ],
        "summary": "Show refund details",
        "description": "Shows details for a refund, by ID.",
        "operationId": "payments_payment_v2_refunds_get",
        "security": [
          {
            "payments_payment_v2_Oauth2": [
              "https://uri.paypal.com/services/payments/refund"
            ]
          }
        ]
      }
    },
    "/payments_payouts_batch_v1/v1/payments/payouts": {
      "post": {
        "tags": [
          "payouts"
        ],
        "summary": "Create batch payout",
        "description": "Creates a batch payout. In the JSON request body, pass a `sender_batch_header` and an `items` array. The `sender_batch_header` defines how to handle the payout. The `items` array defines the payout items.<br/>You can make payouts to one or more recipients.<blockquote><strong>Notes:</strong> <ul><li><p>PayPal does not process duplicate payouts. If you specify a <code>sender_batch_id</code> that was used in the last 30 days, the API rejects the request with an error message[...]",
        "operationId": "payments_payouts_batch_v1_payouts_post",
        "security": [
          {
            "payments_payouts_batch_v1_Oauth2": [
              "https://uri.paypal.com/payments/payouts"
            ]
          }
        ]
      }
    },
    "/payments_payouts_batch_v1/v1/payments/payouts/{id}": {
      "get": {
        "tags": [
          "payouts"
        ],
        "summary": "Show payout batch details",
        "description": "Shows the latest status of a batch payout. Includes the transaction status and other data for individual payout items.",
        "operationId": "payments_payouts_batch_v1_payouts_get",
        "security": [
          {
            "payments_payouts_batch_v1_Oauth2": [
              "https://uri.paypal.com/payments/payouts"
            ]
          }
        ]
      }
    },
    "/payments_payouts_batch_v1/v1/payments/payouts-item/{payout_item_id}": {
      "get": {
        "tags": [
          "payouts-item"
        ],
        "summary": "Show payout item details",
        "description": "Shows details for a payout item, by ID. A <code>payout_item_id</code> helps you identify denied payments. If a payment is denied, you can use the <code>payout_item_id</code> to identify the payment even if it lacks a <code>transaction_id</code>.",
        "operationId": "payments_payouts_batch_v1_payouts_item_get",
        "security": [
          {
            "payments_payouts_batch_v1_Oauth2": [
              "https://uri.paypal.com/payments/payouts"
            ]
          }
        ]
      }
    },
    "/payments_payouts_batch_v1/v1/payments/payouts-item/{payout_item_id}/cancel": {
      "post": {
        "tags": [
          "payouts-item"
        ],
        "summary": "Cancel unclaimed payout item",
        "description": "Cancels an unclaimed payout item, by ID. If no one claims the unclaimed item within 30 days, the API automatically returns the funds to the sender. Use this call to cancel the unclaimed item before the automatic 30-day refund. You can cancel payout items with a <code>transaction_status</code> of <code>UNCLAIMED</code>.",
        "operationId": "payments_payouts_batch_v1_payouts_item_cancel",
        "security": [
          {
            "payments_payouts_batch_v1_Oauth2": [
              "https://uri.paypal.com/payments/payouts"
            ]
          }
        ]
      }
    },
    "/reporting_transactions_v1/v1/reporting/transactions": {
      "get": {
        "tags": [
          "transactions"
        ],
        "summary": "List transactions",
        "description": "Lists transactions. Specify one or more query parameters to filter the transaction that appear in the response.<blockquote><strong>Notes:</strong> <ul><li>If you specify one or more optional query parameters, the <code>ending_balance</code> response field is empty.</li><li>It takes a maximum of three hours for executed transactions to appear in the list transactions call.</li><li>This call lists transaction for the previous three years.</li></ul></blockquote>",
        "operationId": "reporting_transactions_v1_search_get",
        "security": [
          {
            "reporting_transactions_v1_Oauth2": [
              "https://uri.paypal.com/services/reporting/search/read"
            ]
          }
        ]
      }
    },
    "/reporting_transactions_v1/v1/reporting/balances": {
      "get": {
        "tags": [
          "balances"
        ],
        "summary": "List all balances",
        "description": "List all balances. Specify date time to list balances for that time that appear in the response.<blockquote><strong>Notes:</strong> <ul><li>It takes a maximum of three hours for balances to appear in the list balances call.</li><li>This call lists balances upto the previous three years.</li></ul></blockquote>",
        "operationId": "reporting_transactions_v1_balances_get",
        "security": [
          {
            "reporting_transactions_v1_Oauth2": [
              "https://uri.paypal.com/services/reporting/balances/read"
            ]
          }
        ]
      }
    },
    "/shipping_shipment_tracking_v1/v1/shipping/trackers-batch": {
      "post": {
        "tags": [
          "trackers-batch"
        ],
        "summary": "Add tracking information for multiple PayPal transactions",
        "description": "<blockquote><strong>Deprecation notice:</strong> Adding tracking details for an order through <code>/v1/shipping/trackers-batch</code> is deprecated as its a legacy way of integration. Use the new <a href=\"/docs/tracking/orders-api/integrate/\">Orders v2 API</a> to share tracking details with PayPal.</blockquote>Adds tracking information, with or without tracking numbers, for multiple PayPal transactions. Accepts up to 20 tracking IDs. For more information, see <a href=\[...]",
        "operationId": "shipping_shipment_tracking_v1_trackers_batch_post",
        "security": [
          {
            "shipping_shipment_tracking_v1_Oauth2": [
              "https://uri.paypal.com/services/shipping/trackers/readwrite"
            ]
          }
        ]
      }
    },
    "/shipping_shipment_tracking_v1/v1/shipping/trackers": {
      "post": {
        "tags": [
          "trackers"
        ],
        "summary": "Add tracking information for PayPal transaction",
        "description": "Adds tracking information for a PayPal transaction.",
        "operationId": "shipping_shipment_tracking_v1_trackers_post",
        "security": [
          {
            "shipping_shipment_tracking_v1_Oauth2": [
              "https://uri.paypal.com/services/shipping/trackers/readwrite"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "trackers"
        ],
        "summary": "List tracking information",
        "description": "Lists tracking information that meet search criteria. The tracking ID is required but the tracking number is optional.",
        "operationId": "shipping_shipment_tracking_v1_trackers_batch_get",
        "security": [
          {
            "shipping_shipment_tracking_v1_Oauth2": [
              "https://uri.paypal.com/services/shipping/trackers/read",
              "https://uri.paypal.com/services/shipping/trackers/readwrite"
            ]
          }
        ]
      }
    },
    "/shipping_shipment_tracking_v1/v1/shipping/trackers/{id}": {
      "put": {
        "tags": [
          "trackers"
        ],
        "summary": "Update or cancel tracking information for PayPal transaction",
        "description": "Updates or cancels the tracking information for a PayPal transaction, by ID. To cancel tracking information, call this method and set the status to CANCELLED. For more information, see <a href=\"/docs/tracking/tracking-api/integrate/#link-updateorcanceltrackinginformation\">Update or cancel tracking information</a>.",
        "operationId": "shipping_shipment_tracking_v1_trackers_put",
        "security": [
          {
            "shipping_shipment_tracking_v1_Oauth2": [
              "https://uri.paypal.com/services/shipping/trackers/readwrite"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "trackers"
        ],
        "summary": "Show tracking information",
        "description": "Shows tracking information, by tracker ID, for a PayPal transaction.",
        "operationId": "shipping_shipment_tracking_v1_trackers_get",
        "security": [
          {
            "shipping_shipment_tracking_v1_Oauth2": [
              "https://uri.paypal.com/services/shipping/trackers/read",
              "https://uri.paypal.com/services/shipping/trackers/readwrite"
            ]
          }
        ]
      }
    },
    "/vault_payment_tokens_v3/v3/vault/payment-tokens": {
      "post": {
        "tags": [
          "payment-tokens"
        ],
        "summary": "Create payment token for a given payment source",
        "description": "Creates a Payment Token from the given payment source and adds it to the Vault of the associated customer.",
        "operationId": "vault_payment_tokens_v3_payment_tokens_create",
        "security": [
          {
            "vault_payment_tokens_v3_Oauth2": [
              "https://uri.paypal.com/services/vault/payment-tokens/readwrite"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "payment-tokens"
        ],
        "summary": "List all payment tokens",
        "description": "Returns all payment tokens for a customer.",
        "operationId": "vault_payment_tokens_v3_customer_payment_tokens_get",
        "security": [
          {
            "vault_payment_tokens_v3_Oauth2": [
              "https://uri.paypal.com/services/vault/payment-tokens/readwrite"
            ]
          }
        ]
      }
    },
    "/vault_payment_tokens_v3/v3/vault/payment-tokens/{id}": {
      "get": {
        "tags": [
          "payment-tokens"
        ],
        "summary": "Retrieve a payment token",
        "description": "Returns a readable representation of vaulted payment source associated with the payment token id.",
        "operationId": "vault_payment_tokens_v3_payment_tokens_get",
        "security": [
          {
            "vault_payment_tokens_v3_Oauth2": [
              "https://uri.paypal.com/services/vault/payment-tokens/readwrite"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "payment-tokens"
        ],
        "summary": "Delete payment token",
        "description": "Delete the payment token associated with the payment token id.",
        "operationId": "vault_payment_tokens_v3_payment_tokens_delete",
        "security": [
          {
            "vault_payment_tokens_v3_Oauth2": [
              "https://uri.paypal.com/services/vault/payment-tokens/readwrite"
            ]
          }
        ]
      }
    },
    "/vault_payment_tokens_v3/v3/vault/setup-tokens": {
      "post": {
        "tags": [
          "setup-tokens"
        ],
        "summary": "Create a setup token",
        "description": "Creates a Setup Token from the given payment source and adds it to the Vault of the associated customer.",
        "operationId": "vault_payment_tokens_v3_setup_tokens_create",
        "security": [
          {
            "vault_payment_tokens_v3_Oauth2": [
              "https://uri.paypal.com/services/vault/payment-tokens/read"
            ]
          }
        ]
      }
    },
    "/vault_payment_tokens_v3/v3/vault/setup-tokens/{id}": {
      "get": {
        "tags": [
          "setup-tokens"
        ],
        "summary": "Retrieve a setup token",
        "description": "Returns a readable representation of temporarily vaulted payment source associated with the setup token id.",
        "operationId": "vault_payment_tokens_v3_setup_tokens_get",
        "security": [
          {
            "vault_payment_tokens_v3_Oauth2": [
              "https://uri.paypal.com/services/vault/payment-tokens/read"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Oauth2": {
        "type": "oauth2",
        "description": "Oauth 2.0 authentication",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/v1/oauth2/token",
            "scopes": {
              "https://uri.paypal.com/services/subscriptions": "Manage plan & subscription"
            }
          }
        }
      },
      "catalogs_products_v1_Oauth2": {
        "type": "oauth2",
        "description": "Oauth 2.0 authentication",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/v1/oauth2/token",
            "scopes": {
              "https://uri.paypal.com/services/subscriptions": "Create and manage products"
            }
          }
        }
      },
      "checkout_orders_v2_Oauth2": {
        "type": "oauth2",
        "description": "Oauth 2.0 authentication",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/v1/oauth2/token",
            "scopes": {
              "https://uri.paypal.com/services/payments/payment": "Manage payments and checkout workflow.",
              "https://uri.paypal.com/services/payments/payment/reference-transaction": "Permission to initiate reference transaction",
              "https://uri.paypal.com/services/payments/initiatepayment": "Initiates payments and checkout workflows.",
              "https://uri.paypal.com/services/payments/orders/deprecating-jssdk-migration-for-limited-merchants": "Allows client-side integration on Create, Get, Patch, Authorize & Capture Order endpoints.",
              "https://uri.paypal.com/services/payments/orders/client_sdk_orders_api": "Enables secure client-side integration on confirm payment source endpoint"
            }
          }
        }
      },
      "customer_disputes_v1_Oauth2": {
        "type": "oauth2",
        "description": "Oauth 2.0 authentication",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/v1/oauth2/token",
            "scopes": {
              "https://uri.paypal.com/services/disputes/read-seller": "This privilege allows client to read and search a disputes of a merchant but gets only a limited and allowed set of fields back .",
              "https://uri.paypal.com/services/disputes/read-buyer": "This privilege allows client to read and search disputes but returns a limited and allowed set of fields back.",
              "https://uri.paypal.com/services/disputes/read-ebay": "This privilege allows client to read and search a disputes of an user but gets only a limited and allowed set of fields back to ebay.",
              "https://uri.paypal.com/services/disputes/read": "This privilege allows client to read and search a dispute of an user with all fields.",
              "https://uri.paypal.com/services/disputes/webhooks": "This privilege allows webhook platform to read a dispute event",
              "https://uri.paypal.com/services/disputes/create": "This privilege allows client to validate eligibility and create a dispute on his transaction(s).",
              "https://uri.paypal.com/services/disputes/update-seller": "This privilege allows client to update a dispute (Merchant actions).",
              "https://uri.paypal.com/services/disputes/update-buyer": "This privilege allows client to update a dispute (customer actions).",
              "https://uri.paypal.com/services/referred-disputes/readwrite": "This privilege allows client to read and update a referred dispute.",
              "https://uri.paypal.com/services/disputes/read-partner": "This privilege allows client to read and search disputes but returns a limited and allowed set of fields back.",
              "https://uri.paypal.com/services/disputes/update-partner": "This privilege allows client to update a dispute (Partner actions)."
            }
          }
        }
      },
      "customer_partner_referrals_v2_Oauth2": {
        "type": "oauth2",
        "description": "Oauth 2.0 authentication",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/v1/oauth2/token",
            "scopes": {
              "https://uri.paypal.com/services/customer/partner": "Manage seller resources.",
              "https://uri.paypal.com/services/customer/partner-referrals/readwrite": "Manage external referral data with PayPal",
              "https://uri.paypal.com/services/customer/partner-referrals": "Manage referral data shared by Partner with PayPal. To be used by only internal apps"
            }
          }
        }
      },
      "invoicing_v2_Oauth2": {
        "type": "oauth2",
        "description": "Oauth 2.0 authentication",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/v1/oauth2/token",
            "scopes": {
              "https://uri.paypal.com/services/invoicing/invoices/read": "For Reading the invoice details.",
              "https://uri.paypal.com/services/invoicing/invoices/readwrite": "For managing (Create, Update, Delete) invoice.",
              "https://uri.paypal.com/services/invoicing/internal": "Manage invoice resource internal clients."
            }
          }
        }
      },
      "notifications_webhooks_v1_Oauth2": {
        "type": "oauth2",
        "description": "Oauth 2.0 authentication",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/v1/oauth2/token",
            "scopes": {
              "https://uri.paypal.com/services/applications/webhooks": "Access/update Webhooks.",
              "https://uri.paypal.com/services/applications/verify-webhook-signature": "Verify Webhook Signature"
            }
          }
        }
      },
      "payment_experience_web_experience_profiles_v1_Oauth2": {
        "type": "oauth2",
        "description": "Oauth 2.0 authentication",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/v1/oauth2/token",
            "scopes": {
              "https://uri.paypal.com/services/payments/payment": "New special privileged scope available for payment and manage payment experience profiles. Available to internal clients only.",
              "https://uri.paypal.com/services/payments/realtimepayment": "Permission to do any real-time payment and manage-payment experience profiles with support for sale, authorize, and order intents."
            }
          }
        }
      },
      "payments_payment_v2_Oauth2": {
        "type": "oauth2",
        "description": "OAuth 2.0 authentication",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/v1/oauth2/token",
            "scopes": {
              "https://uri.paypal.com/services/payments/payment/authcapture": "Permission to do non-real time payments like capture on authorization",
              "https://uri.paypal.com/services/payments/refund": "Permission to initiate a refund on a capture transaction",
              "https://uri.paypal.com/services/payments/non-referenced-credit": "Permission to initiate non referenced credit",
              "https://uri.paypal.com/services/payments/realtimepayment": "Permission to do any real time payment, with support for sale/authorize/order intents",
              "https://uri.paypal.com/services/payments/reversepayment": "Permission to do any reverse payment",
              "https://uri.paypal.com/services/payments/payments-ready": "Permission to get information about payment readiness.",
              "Braintree:PaymentsReady": "Permission to call PaymentsReady via BrainTree SDK.",
              "https://uri.paypal.com/services/payments/client-payments-eligibility": "Permission to get information about merchant's eligible payment methods."
            }
          }
        }
      },
      "payments_payouts_batch_v1_Oauth2": {
        "type": "oauth2",
        "description": "Oauth 2.0 authentication",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/v1/oauth2/token",
            "scopes": {
              "https://uri.paypal.com/payments/payouts": "Payout to a list of recipients.",
              "https://uri.paypal.com/services/payments/payouts-item/reverse": "For reversing a completed payout item.",
              "https://uri.paypal.com/services/payments/payout-applications/status": "For retrieving payouts application status",
              "https://uri.paypal.com/services/payments/payout-applications/update-status": "For updating payouts application status"
            }
          }
        }
      },
      "reporting_transactions_v1_Oauth2": {
        "type": "oauth2",
        "description": "Oauth 2.0 authentication",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/v1/oauth2/token",
            "scopes": {
              "https://uri.paypal.com/services/reporting/search/read": "Transactions Search",
              "https://uri.paypal.com/services/reporting/balances/read": "List Balances"
            }
          }
        }
      },
      "shipping_shipment_tracking_v1_Oauth2": {
        "type": "oauth2",
        "description": "Oauth 2.0 authentication",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/v1/oauth2/token",
            "scopes": {
              "https://uri.paypal.com/services/shipping/trackers/readwrite": "Create or update tracking information",
              "https://uri.paypal.com/services/shipping/trackers/read": "Retrieve tracking information"
            }
          }
        }
      },
      "vault_payment_tokens_v3_Oauth2": {
        "type": "oauth2",
        "description": "Oauth 2.0 authentication",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/v1/oauth2/token",
            "scopes": {
              "https://uri.paypal.com/services/vault/payment-tokens/readwrite": "Manage payment instruments",
              "https://uri.paypal.com/services/vault/payment-tokens/read": "Permission to only read from vault",
              "https://uri.paypal.com/services/vault/customers/read": "Permission to read customer information.",
              "https://uri.paypal.com/services/vault/customers/readwrite": "Permission to create/update customer information."
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "plans",
      "description": "Use the `/billing/plans` resource to create and manage plans."
    },
    {
      "name": "subscriptions",
      "description": "Use the `/billing/subscriptions` resource to create and manage subscriptions."
    },
    {
      "name": "subscriptions-buyer-consent",
      "description": "Use the `/billing/subscriptions/approval-tokens` resource for subscriptions buyer consent flow."
    },
    {
      "name": "products",
      "description": "Use `/products` resource to create and manage products."
    },
    {
      "name": "orders",
      "description": "Use the `/orders` resource to create, update, retrieve, authorize, capture and track orders."
    },
    {
      "name": "trackers",
      "description": "Use the `/trackers` resource to update and retrieve tracking information for PayPal orders."
    },
    {
      "name": "externalcallback",
      "description": "PayPal will use the callback url defined in the create order request to send merchants shipping address and shipping options data while the buyer is in the PayPal checkout."
    },
    {
      "name": "disputes",
      "description": "Use the `/disputes` resource to list disputes, create disputes, show dispute details, and partially a dispute. Normally, an agent at PayPal creates disputes but now you can run test cases in the sandbox that create disputes."
    },
    {
      "name": "disputes-actions",
      "description": "Use the `/disputes` resource with a dispute ID and an action to:<ul><li>Accept a claim.</li><li>Accept an offer to resolve a dispute.</li><li>Acknowledge the return of an item related to a dispute.</li><li>Settle a dispute.</li><li>Appeal a dispute.</li><li>Cancel a dispute.</li><li>Change the reason for a dispute.</li><li>Deny an offer to resolve dispute.</li><li>Escalate a dispute to a claim.</li><li>Make an offer to resolve a dispute.</li><li>Make an offer to resolve a d[...]"
    },
    {
      "name": "referred-disputes",
      "description": "Use the `/customer/referred-disputes` resource to create a dispute for a referred case that was created by a partner or marketplace, show details for a referred dispute, by ID, notify referred refunds completed to PayPal, notify PayPal about referred dispute adjudication updates, and determine the dispute eligibility for referred disputes."
    },
    {
      "name": "validate-eligibility",
      "description": "Use the `/validate-eligibility/` resource to determine whether you can create a case for a transaction."
    },
    {
      "name": "compute-metrics",
      "description": "Use the `/compute-metrics` resource to provide metrics for all disputes."
    },
    {
      "name": "validate-referred-dispute-eligibility",
      "description": "Use the `/validate-referred-dispute-eligibility` resource to determine whether you can create a referred case for a transaction, by encrypted transaction ID."
    },
    {
      "name": "referred-disputes-actions",
      "description": "Use the `/referred-disputes` resource with a dispute ID and an action to notify PayPal about adjudication updates for a referred dispute and notify PayPal about a refund for a referred dispute."
    },
    {
      "name": "partner-actions",
      "description": "Use the `/disputes/{id}/partner-actions/` resource to show dispute action details and partially update a dispute action."
    },
    {
      "name": "search-suggestions",
      "description": "Use the `/search-suggestions` resource to show search suggestions."
    },
    {
      "name": "dispute-events",
      "description": "Use the `/dispute-events` resource to send dispute events."
    },
    {
      "name": "refund-preference",
      "description": "Use the `/disputes/{id}/provide-refund-preference` resource to provide refund preferences for the dispute."
    },
    {
      "name": "return-compensation",
      "description": "Use the `/disputes/{id}/return-compensation` resource to return the compensation on the dispute provided by PayPal to the customer."
    },
    {
      "name": "partner-referrals",
      "description": "Enables you to create and get information about shared customer data."
    },
    {
      "name": "invoices",
      "description": "Use the `/invoices` resource to create, update, and send invoices and invoice reminders. To manage invoices, you can also list invoices, show details for invoices, delete draft invoices, and cancel sent invoices. You can also record payments for invoices to mark them as fully or partially paid, or record refunds for invoices to mark them as fully or partially refunded. You can create QR codes for invoices that can be scanned, viewed, and paid by a mobile phone."
    },
    {
      "name": "search-invoices",
      "description": "Use the `/search-invoices` resource to search for and list invoices that match search criteria."
    },
    {
      "name": "templates",
      "description": "Use the `/templates` resource to create, list, show details for, update, and delete invoice templates. Use the `/templates` resource when you create a third-party invoicing application. For instance, a business can create a template with predefined invoice data. Later, the business can select the template to populate the invoice data.<blockquote><strong>Note:</strong> To upload a logo to display on an invoice, you can use the <strong>Template Settings</strong> dashboard to [...]"
    },
    {
      "name": "merchant-config",
      "description": "Use the `/merchant-config` resource to create, update and show details of merchant configuration."
    },
    {
      "name": "estimates",
      "description": "Use the /estimate resource to create, update, and send estimates."
    },
    {
      "name": "batch-tasks",
      "description": "Use the /batch-tasks resource to create, delete and retrieve batch related tasks."
    },
    {
      "name": "stored-discounts",
      "description": "Use the /stored-discounts resource to create and retrieve stored-discounts are specific to merchants"
    },
    {
      "name": "Search Enhancement",
      "description": "This section contains the list of api, used to power invoicing search based on Index Organised Table(s)."
    },
    {
      "name": "Invoicing Multi Tenancy",
      "description": "This section contains api to get the tenant config details."
    },
    {
      "name": "Invoice Notification",
      "description": "Use the /email-status-feedback resource to post the status update against invoicing emails."
    },
    {
      "name": "Customer Feedbacks",
      "description": "Use the /customer-feedbacks resource to create and retrieve feedbacks specific to merchants."
    },
    {
      "name": "Insights",
      "description": "Use the /insights resource to retrieve aggregated metrics specific to merchants."
    },
    {
      "name": "invoicing-product-features",
      "description": "This section contains the list of invoicing-product-features related api's."
    },
    {
      "name": "conditional-rules",
      "description": "This section contains api's related to conditional rules."
    },
    {
      "name": "invoice-payment-attempt",
      "description": "This section contains api's related to invoice payment attempt."
    },
    {
      "name": "connections",
      "description": "Use the `accounting-sync/merchants/connections` resource to get active connections list."
    },
    {
      "name": "invoice-connection-details",
      "description": "Use the `accounting-sync/invoices/{id}/connections` resource to get active connections list."
    },
    {
      "name": "Invoicing themes",
      "description": "Use the /themes resource to create, update and get details of themes related to merchants."
    },
    {
      "name": "webhooks",
      "description": "Use the `/webhooks` resource to subscribe your webhook listener to events, list webhooks for an app, show details for, update, delete, and list event subscriptions for webhooks."
    },
    {
      "name": "webhooks-lookup",
      "description": "Use the `/webhooks-lookup` resource to create, list, show details for, and delete webhook lookups."
    },
    {
      "name": "verify-webhook-signature",
      "description": "Use the `/verify-webhook-signature` resource to verify a webhook signature."
    },
    {
      "name": "webhooks-event-types",
      "description": "Use the `/webhooks-event-types` resource to list available events to which any webhook can subscribe."
    },
    {
      "name": "webhooks-events",
      "description": "Use the `/webhooks-events` resource to list, show details for, and resend event notifications."
    },
    {
      "name": "simulate-event",
      "description": "Use the `/simulate-event` resource to use a sample payload to simulate a webhook event. The events that this call generates only serve to validate the connection to the listener URL and to show how webhook events look. <blockquote><strong>Note:</strong> You can also use the <a href=\"/docs/api/notifications/webhooks/simulator/\">Webhooks simulator</a> to simulate webhook events.</blockquote>"
    },
    {
      "name": "publish-event-with-payload",
      "description": "Use the `/publish-event-with-payload` resource to publish an event with a specified payload."
    },
    {
      "name": "publish-event-with-reference",
      "description": "Use the `/publish-event-with-reference` resource to publish an event with a specified reference."
    },
    {
      "name": "webhook-event-delivery-status",
      "description": "Use the `/webhook-event-delivery-status` resource to show the webhook event send status."
    },
    {
      "name": "webhooks-error-types",
      "description": "Use the `/error-types` resource to create and list available webhook error types."
    },
    {
      "name": "webhooks-errors",
      "description": "Use the `/webhooks-errors` resource to create, list, show details for, and update webhook errors."
    },
    {
      "name": "batch-resend",
      "description": "Use the `/batch-resend` resource to send out IPN/Webhooks in batches."
    },
    {
      "name": "web-profiles",
      "description": "Use the `/payment-experience/web-profiles` resource to create, show details for, list, update, partially update, and delete web experience profiles."
    },
    {
      "name": "authorizations",
      "description": "Use the `/authorizations` resource to show details for, capture payment for, reauthorize, and void authorized payments."
    },
    {
      "name": "captures",
      "description": "Use the `/captures` resource to show details for and refund a captured payment."
    },
    {
      "name": "refunds",
      "description": "Use the `/refunds` resource to show refund details."
    },
    {
      "name": "assets",
      "description": "Assets APIs for Checkout"
    },
    {
      "name": "cancel-payment",
      "description": "Use the <code>/cancel-payment</code> resource to cancel an order capture or order authorization by <code>PayPal-Request-Id</code>. The merchant triggers the cancel action."
    },
    {
      "name": "find-eligible-methods",
      "description": "Use the `/find-eligible-methods` resource to show list of eligible payment methods for given customer/order context."
    },
    {
      "name": "payment-resource-operations",
      "description": "Use the `/payment-resource-operations` resource to show verifications details."
    },
    {
      "name": "find-bin-details",
      "description": "Use the `/find-bin-details` resource to determine PayPal supported networks and retrieve BIN details for given card and payee."
    },
    {
      "name": "payouts",
      "description": "Use the `/payouts` resource to create a batch payout, update the status for a batch payout, show the status of a batch payout with the transaction status and other data for individual payout items, and request approval for a batch payout."
    },
    {
      "name": "payouts-item",
      "description": "Use the `/payouts-item` resource to show payout item details and cancel an unclaimed payout item."
    },
    {
      "name": "payouts-statistics",
      "description": "Use the `/payouts-statistics` resource to show statistics for a batch payout by date range."
    },
    {
      "name": "payouts-disbursement-notifications",
      "description": "Use the `payouts/disbursement-notifications` resource for status updates from <code>VENMO</code>"
    },
    {
      "name": "payout-application-status",
      "description": "Use the `/payout-applications` resource to fetch and update payout status of the application."
    },
    {
      "name": "transactions",
      "description": "Use the `/transactions` resource to list transactions."
    },
    {
      "name": "partner-transactions",
      "description": "Use the `/partner-transactions` resource to list transactions."
    },
    {
      "name": "balances",
      "description": "Use the `/balances` resource to list balances."
    },
    {
      "name": "trackers-batch",
      "description": "Use the `/trackers-batch` resource to add tracking information for multiple PayPal transactions."
    },
    {
      "name": "carriers-recommend",
      "description": "Use the `/carriers-recommendations` to detect the possible carriers corresponding the tracking info from tracking aggregator."
    },
    {
      "name": "carriers",
      "description": "Use the `/carriers` resource to list/detect all the carriers available for tracking in PayPal and its subsidiary."
    },
    {
      "name": "shipments",
      "description": "Use the `/shipments` resource to fetch all the shipments associated with a given Paypal Account Id."
    },
    {
      "name": "shipment-tracker",
      "description": "Use the `/shipment-tracker` resource to track the shipment."
    },
    {
      "name": "unsubscribe-shipment-tracking",
      "description": "Use the `/unsubscribe-shipment-tracking` resource to unsubscribe from multiple shipments."
    },
    {
      "name": "shipment-trackings-update",
      "description": "Use the `/shipment-trackings-update` resource to update shipments with live tracking data."
    },
    {
      "name": "tracking-shipments",
      "description": "Use the `/tracking-shipments` resource to track shipments."
    },
    {
      "name": "payment-tokens",
      "description": "Use the `/vault/payment-tokens` resource to create, retrieve, and delete a payment token that may optionally be associated with a customer."
    },
    {
      "name": "setup-tokens",
      "description": "Use the `/vault/setup-tokens` resource to create and retrieve temporary vault payment methods."
    },
    {
      "name": "tokens",
      "description": "Use the `/vault/tokens` resource to detokenize a vault token to retrieve details associated to the underlying payment source."
    },
    {
      "name": "tokens-session",
      "description": "Use the `/vault/tokens/{id}/session` resource to read the token session cache and retrieve details associated to the underlying payment source."
    },
    {
      "name": "customers",
      "description": "Use the `/vault/customers` resource to create, update, get and delete a customer."
    },
    {
      "name": "payment-method-credentials",
      "description": "Use the `/vault/payment-method-credentials` resource to create payment method credentials"
    }
  ]
}