// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.SimulateEvent;
using Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.VerifyWebhookSignature;
using Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.Webhooks;
using Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.WebhooksEventTypes;
using Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.WebhooksEvents;
using Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.WebhooksLookup;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications
{
    /// <summary>
    /// Builds and executes requests for operations under \notifications_webhooks_v1\v1\notifications
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NotificationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The simulateEvent property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.SimulateEvent.SimulateEventRequestBuilder SimulateEvent
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.SimulateEvent.SimulateEventRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The verifyWebhookSignature property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.VerifyWebhookSignature.VerifyWebhookSignatureRequestBuilder VerifyWebhookSignature
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.VerifyWebhookSignature.VerifyWebhookSignatureRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooksEvents property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.WebhooksEvents.WebhooksEventsRequestBuilder WebhooksEvents
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.WebhooksEvents.WebhooksEventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooksEventTypes property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.WebhooksEventTypes.WebhooksEventTypesRequestBuilder WebhooksEventTypes
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.WebhooksEventTypes.WebhooksEventTypesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooksLookup property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.WebhooksLookup.WebhooksLookupRequestBuilder WebhooksLookup
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.WebhooksLookup.WebhooksLookupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.NotificationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NotificationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/notifications_webhooks_v1/v1/notifications", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Notifications_webhooks_v1.V1.Notifications.NotificationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NotificationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/notifications_webhooks_v1/v1/notifications", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
