// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.PayPal.OpenApiClient.Payments_payment_v2.V2.Payments.Authorizations;
using Soenneker.PayPal.OpenApiClient.Payments_payment_v2.V2.Payments.Captures;
using Soenneker.PayPal.OpenApiClient.Payments_payment_v2.V2.Payments.Refunds;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.PayPal.OpenApiClient.Payments_payment_v2.V2.Payments
{
    /// <summary>
    /// Builds and executes requests for operations under \payments_payment_v2\v2\payments
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PaymentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The authorizations property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Payments_payment_v2.V2.Payments.Authorizations.AuthorizationsRequestBuilder Authorizations
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Payments_payment_v2.V2.Payments.Authorizations.AuthorizationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The captures property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Payments_payment_v2.V2.Payments.Captures.CapturesRequestBuilder Captures
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Payments_payment_v2.V2.Payments.Captures.CapturesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The refunds property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Payments_payment_v2.V2.Payments.Refunds.RefundsRequestBuilder Refunds
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Payments_payment_v2.V2.Payments.Refunds.RefundsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Payments_payment_v2.V2.Payments.PaymentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PaymentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/payments_payment_v2/v2/payments", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Payments_payment_v2.V2.Payments.PaymentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PaymentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/payments_payment_v2/v2/payments", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
