// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>The type of adjudication.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AdjudicationType
    {
        [EnumMember(Value = "DENY_BUYER")]
        #pragma warning disable CS1591
        DENY_BUYER,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYOUT_TO_BUYER")]
        #pragma warning disable CS1591
        PAYOUT_TO_BUYER,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYOUT_TO_SELLER")]
        #pragma warning disable CS1591
        PAYOUT_TO_SELLER,
        #pragma warning restore CS1591
        [EnumMember(Value = "RECOVER_FROM_SELLER")]
        #pragma warning disable CS1591
        RECOVER_FROM_SELLER,
        #pragma warning restore CS1591
    }
}
