// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>Indicates the type of payment data passed, in case of Non China the payment data is 3DSECURE and for China it is EMV.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Apple_pay_decrypted_token_data_payment_data_type
    {
        [EnumMember(Value = "3DSECURE")]
        #pragma warning disable CS1591
        ThreeDSECURE,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMV")]
        #pragma warning disable CS1591
        EMV,
        #pragma warning restore CS1591
    }
}
