// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// Information about the Payment data obtained by decrypting Apple Pay token.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApplePayDecryptedTokenData : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Apple Pay Hex-encoded device manufacturer identifier. The pattern is defined by an external party and supports Unicode.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceManufacturerId { get; set; }
#nullable restore
#else
        public string DeviceManufacturerId { get; set; }
#endif
        /// <summary>The payment_data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData_payment_data? PaymentData { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData_payment_data PaymentData { get; set; }
#endif
        /// <summary>Indicates the type of payment data passed, in case of Non China the payment data is 3DSECURE and for China it is EMV.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData_payment_data_type? PaymentDataType { get; set; }
        /// <summary>The tokenized_card property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData_tokenized_card? TokenizedCard { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData_tokenized_card TokenizedCard { get; set; }
#endif
        /// <summary>The transaction_amount property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData_transaction_amount? TransactionAmount { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData_transaction_amount TransactionAmount { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData"/> and sets the default values.
        /// </summary>
        public ApplePayDecryptedTokenData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "device_manufacturer_id", n => { DeviceManufacturerId = n.GetStringValue(); } },
                { "payment_data", n => { PaymentData = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData_payment_data>(global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData_payment_data.CreateFromDiscriminatorValue); } },
                { "payment_data_type", n => { PaymentDataType = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData_payment_data_type>(); } },
                { "tokenized_card", n => { TokenizedCard = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData_tokenized_card>(global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData_tokenized_card.CreateFromDiscriminatorValue); } },
                { "transaction_amount", n => { TransactionAmount = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData_transaction_amount>(global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData_transaction_amount.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("device_manufacturer_id", DeviceManufacturerId);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData_payment_data>("payment_data", PaymentData);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData_payment_data_type>("payment_data_type", PaymentDataType);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData_tokenized_card>("tokenized_card", TokenizedCard);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenData_transaction_amount>("transaction_amount", TransactionAmount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
