// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// Apple Pay tokenized credit card used to pay.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApplePayDecryptedTokenDataTokenizedCard : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Additional attributes associated with the use of this card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.CardAttributesComposed? Attributes { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.CardAttributesComposed Attributes { get; set; }
#endif
        /// <summary>The billing_address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.CardBillingAddress? BillingAddress { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.CardBillingAddress BillingAddress { get; set; }
#endif
        /// <summary>The card brand or network. Typically used in the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.CardBrandComposed? Brand { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.CardBrandComposed Brand { get; set; }
#endif
        /// <summary>The card brand or network. Typically used in the response. &lt;b&gt;DEPRECATED&lt;/b&gt;&lt;br&gt;&lt;table&gt;&lt;tr&gt;&lt;th&gt;See&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;type&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.CardCardType? CardType { get; private set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.CardCardType CardType { get; private set; }
#endif
        /// <summary>The year and month, in ISO-8601 `YYYY-MM` date format. See [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Expiry { get; set; }
#nullable restore
#else
        public string Expiry { get; set; }
#endif
        /// <summary>The identifier of the instrument.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The last digits of the payment card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastDigits { get; private set; }
#nullable restore
#else
        public string LastDigits { get; private set; }
#endif
        /// <summary>The card holder&apos;s name as it appears on the card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The primary account number (PAN) for the payment card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Number { get; set; }
#nullable restore
#else
        public string Number { get; set; }
#endif
        /// <summary>The three- or four-digit security code of the card. Also known as the CVV, CVC, CVN, CVE, or CID. This parameter cannot be present in the request when `payment_initiator=MERCHANT`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecurityCode { get; set; }
#nullable restore
#else
        public string SecurityCode { get; set; }
#endif
        /// <summary>The payment card type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.CardTypeComposed? Type { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.CardTypeComposed Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenDataTokenizedCard"/> and sets the default values.
        /// </summary>
        public ApplePayDecryptedTokenDataTokenizedCard()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenDataTokenizedCard"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenDataTokenizedCard CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.ApplePayDecryptedTokenDataTokenizedCard();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attributes", n => { Attributes = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CardAttributesComposed>(global::Soenneker.PayPal.OpenApiClient.Models.CardAttributesComposed.CreateFromDiscriminatorValue); } },
                { "billing_address", n => { BillingAddress = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CardBillingAddress>(global::Soenneker.PayPal.OpenApiClient.Models.CardBillingAddress.CreateFromDiscriminatorValue); } },
                { "brand", n => { Brand = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CardBrandComposed>(global::Soenneker.PayPal.OpenApiClient.Models.CardBrandComposed.CreateFromDiscriminatorValue); } },
                { "card_type", n => { CardType = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CardCardType>(global::Soenneker.PayPal.OpenApiClient.Models.CardCardType.CreateFromDiscriminatorValue); } },
                { "expiry", n => { Expiry = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "last_digits", n => { LastDigits = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "number", n => { Number = n.GetStringValue(); } },
                { "security_code", n => { SecurityCode = n.GetStringValue(); } },
                { "type", n => { Type = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CardTypeComposed>(global::Soenneker.PayPal.OpenApiClient.Models.CardTypeComposed.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CardAttributesComposed>("attributes", Attributes);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CardBillingAddress>("billing_address", BillingAddress);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CardBrandComposed>("brand", Brand);
            writer.WriteStringValue("expiry", Expiry);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("number", Number);
            writer.WriteStringValue("security_code", SecurityCode);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CardTypeComposed>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
