// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>The tenure type of the billing cycle. In case of a plan having trial cycle, only 2 trial cycles are allowed per plan.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Billing_cycle_tenure_type
    {
        [EnumMember(Value = "REGULAR")]
        #pragma warning disable CS1591
        REGULAR,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRIAL")]
        #pragma warning disable CS1591
        TRIAL,
        #pragma warning restore CS1591
    }
}
