// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// The billing cycle details to override at subscription level. The subscription billing cycle definition has to adhere to the plan billing cycle definition.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Billing_cycle_override : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The pricing scheme details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Pricing_scheme? PricingScheme { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Pricing_scheme PricingScheme { get; set; }
#endif
        /// <summary>The order in which this cycle is to run among other billing cycles. For example, a trial billing cycle has a `sequence` of `1` while a regular billing cycle has a `sequence` of `2`, so that trial cycle runs before the regular cycle.</summary>
        public int? Sequence { get; set; }
        /// <summary>The number of times this billing cycle gets executed. Trial billing cycles can only be executed a finite number of times (value between &lt;code&gt;1&lt;/code&gt; and &lt;code&gt;999&lt;/code&gt; for &lt;code&gt;total_cycles&lt;/code&gt;). Regular billing cycles can be executed infinite times (value of &lt;code&gt;0&lt;/code&gt; for &lt;code&gt;total_cycles&lt;/code&gt;) or a finite number of times (value between &lt;code&gt;1&lt;/code&gt; and &lt;code&gt;999&lt;/code&gt; for &lt;code&gt;total_cycles&lt;/code&gt;).</summary>
        public int? TotalCycles { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Billing_cycle_override"/> and sets the default values.
        /// </summary>
        public Billing_cycle_override()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Billing_cycle_override"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.Billing_cycle_override CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.Billing_cycle_override();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "pricing_scheme", n => { PricingScheme = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Pricing_scheme>(global::Soenneker.PayPal.OpenApiClient.Models.Pricing_scheme.CreateFromDiscriminatorValue); } },
                { "sequence", n => { Sequence = n.GetIntValue(); } },
                { "total_cycles", n => { TotalCycles = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Pricing_scheme>("pricing_scheme", PricingScheme);
            writer.WriteIntValue("sequence", Sequence);
            writer.WriteIntValue("total_cycles", TotalCycles);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
