// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// Common business information section.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BusinessEntity : global::Soenneker.PayPal.OpenApiClient.Models.Business, IParsable
    {
        /// <summary>The currency range, from the minimum inclusive amount to the maximum inclusive amount.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.CurrencyRange? AnnualSalesVolumeRange { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.CurrencyRange AnnualSalesVolumeRange { get; set; }
#endif
        /// <summary>The currency range, from the minimum inclusive amount to the maximum inclusive amount.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.CurrencyRange? AverageMonthlyVolumeRange { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.CurrencyRange AverageMonthlyVolumeRange { get; set; }
#endif
        /// <summary>Beneficial owners of the entity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.BeneficialOwners? BeneficialOwners { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.BeneficialOwners BeneficialOwners { get; set; }
#endif
        /// <summary>The business goals description. For example, a mission statement.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessDescription { get; set; }
#nullable restore
#else
        public string BusinessDescription { get; set; }
#endif
        /// <summary>The account&apos;s purpose code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.BusinessEntity_purpose_code? PurposeCode { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.BusinessEntity_purpose_code PurposeCode { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.BusinessEntity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.PayPal.OpenApiClient.Models.BusinessEntity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.BusinessEntity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "annual_sales_volume_range", n => { AnnualSalesVolumeRange = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CurrencyRange>(global::Soenneker.PayPal.OpenApiClient.Models.CurrencyRange.CreateFromDiscriminatorValue); } },
                { "average_monthly_volume_range", n => { AverageMonthlyVolumeRange = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CurrencyRange>(global::Soenneker.PayPal.OpenApiClient.Models.CurrencyRange.CreateFromDiscriminatorValue); } },
                { "beneficial_owners", n => { BeneficialOwners = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.BeneficialOwners>(global::Soenneker.PayPal.OpenApiClient.Models.BeneficialOwners.CreateFromDiscriminatorValue); } },
                { "business_description", n => { BusinessDescription = n.GetStringValue(); } },
                { "purpose_code", n => { PurposeCode = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.BusinessEntity_purpose_code>(global::Soenneker.PayPal.OpenApiClient.Models.BusinessEntity_purpose_code.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CurrencyRange>("annual_sales_volume_range", AnnualSalesVolumeRange);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CurrencyRange>("average_monthly_volume_range", AverageMonthlyVolumeRange);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.BeneficialOwners>("beneficial_owners", BeneficialOwners);
            writer.WriteStringValue("business_description", BusinessDescription);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.BusinessEntity_purpose_code>("purpose_code", PurposeCode);
        }
    }
}
#pragma warning restore CS0618
