// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// Card Verification details including the authorization details and 3D SECURE details.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CardVerificationDetails : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The currency and amount for a financial transaction, such as a balance or payment due.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.VaultPaymentTokensV3Money? Amount { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.VaultPaymentTokensV3Money Amount { get; set; }
#endif
        /// <summary>DEPRECATED. This field is DEPRECATED. Please find the date data in the &apos;date&apos; field under the &apos;network_transaction_reference&apos; object instead of the &apos;verification&apos; object.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Date { get; set; }
#nullable restore
#else
        public string Date { get; set; }
#endif
        /// <summary>The card network or brand. Applies to credit, debit, gift, and payment cards.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.VaultPaymentTokensV3CardBrand? Network { get; set; }
        /// <summary>DEPRECATED. This field is DEPRECATED. Please find the network transaction id data in the &apos;id&apos; field under the &apos;network_transaction_reference&apos; object instead of the &apos;verification&apos; object.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NetworkTransactionId { get; set; }
#nullable restore
#else
        public string NetworkTransactionId { get; set; }
#endif
        /// <summary>The processor response information for payment requests, such as direct credit card transactions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.CardVerificationDetailsProcessorResponse? ProcessorResponse { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.CardVerificationDetailsProcessorResponse ProcessorResponse { get; set; }
#endif
        /// <summary>DEPRECATED. This field is DEPRECATED. Please find the 3D secure authentication data in the &apos;three_d_secure&apos; object under the &apos;authentication_result&apos; object instead of the &apos;verification&apos; object.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.CardVerificationDetails_three_d_secure? ThreeDSecure { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.CardVerificationDetails_three_d_secure ThreeDSecure { get; set; }
#endif
        /// <summary>The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.&lt;blockquote&gt;&lt;strong&gt;Note:&lt;/strong&gt; The regular expression provides guidance but does not reject all invalid dates.&lt;/blockquote&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Time { get; set; }
#nullable restore
#else
        public string Time { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.CardVerificationDetails"/> and sets the default values.
        /// </summary>
        public CardVerificationDetails()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.CardVerificationDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.CardVerificationDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.CardVerificationDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VaultPaymentTokensV3Money>(global::Soenneker.PayPal.OpenApiClient.Models.VaultPaymentTokensV3Money.CreateFromDiscriminatorValue); } },
                { "date", n => { Date = n.GetStringValue(); } },
                { "network", n => { Network = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.VaultPaymentTokensV3CardBrand>(); } },
                { "network_transaction_id", n => { NetworkTransactionId = n.GetStringValue(); } },
                { "processor_response", n => { ProcessorResponse = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CardVerificationDetailsProcessorResponse>(global::Soenneker.PayPal.OpenApiClient.Models.CardVerificationDetailsProcessorResponse.CreateFromDiscriminatorValue); } },
                { "three_d_secure", n => { ThreeDSecure = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CardVerificationDetails_three_d_secure>(global::Soenneker.PayPal.OpenApiClient.Models.CardVerificationDetails_three_d_secure.CreateFromDiscriminatorValue); } },
                { "time", n => { Time = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VaultPaymentTokensV3Money>("amount", Amount);
            writer.WriteStringValue("date", Date);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.VaultPaymentTokensV3CardBrand>("network", Network);
            writer.WriteStringValue("network_transaction_id", NetworkTransactionId);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CardVerificationDetailsProcessorResponse>("processor_response", ProcessorResponse);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CardVerificationDetails_three_d_secure>("three_d_secure", ThreeDSecure);
            writer.WriteStringValue("time", Time);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
