// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// Full representation of a Card Payment Token.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Card_response_entity : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Results of Authentication such as 3D Secure.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Card_response_entity_authentication_result? AuthenticationResult { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Card_response_entity_authentication_result AuthenticationResult { get; set; }
#endif
        /// <summary>Address request details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Card_response_entity_billing_address? BillingAddress { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Card_response_entity_billing_address BillingAddress { get; set; }
#endif
        /// <summary>Bank Identification Number (BIN) details used to fund a payment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Vault_payment_tokens_v3_bin_details? BinDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Vault_payment_tokens_v3_bin_details BinDetails { get; set; }
#endif
        /// <summary>The card network or brand. Applies to credit, debit, gift, and payment cards.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.Vault_payment_tokens_v3_card_brand? Brand { get; set; }
        /// <summary>The year and month, in ISO-8601 `YYYY-MM` date format. See [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Expiry { get; set; }
#nullable restore
#else
        public string Expiry { get; set; }
#endif
        /// <summary>The last digits of the payment card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastDigits { get; private set; }
#nullable restore
#else
        public string LastDigits { get; private set; }
#endif
        /// <summary>The card holder&apos;s name as it appears on the card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Previous network transaction reference including id in response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Network_transaction_reference_response? NetworkTransactionReference { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Network_transaction_reference_response NetworkTransactionReference { get; set; }
#endif
        /// <summary>Type of card. i.e Credit, Debit and so on.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.Vault_payment_tokens_v3_card_type? Type { get; set; }
        /// <summary>Card Verification details including the authorization details and 3D SECURE details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Card_verification_details? Verification { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Card_verification_details Verification { get; set; }
#endif
        /// <summary>Verification status of Card.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.Card_verification_status? VerificationStatus { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Card_response_entity"/> and sets the default values.
        /// </summary>
        public Card_response_entity()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Card_response_entity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.Card_response_entity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.Card_response_entity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authentication_result", n => { AuthenticationResult = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Card_response_entity_authentication_result>(global::Soenneker.PayPal.OpenApiClient.Models.Card_response_entity_authentication_result.CreateFromDiscriminatorValue); } },
                { "billing_address", n => { BillingAddress = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Card_response_entity_billing_address>(global::Soenneker.PayPal.OpenApiClient.Models.Card_response_entity_billing_address.CreateFromDiscriminatorValue); } },
                { "bin_details", n => { BinDetails = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Vault_payment_tokens_v3_bin_details>(global::Soenneker.PayPal.OpenApiClient.Models.Vault_payment_tokens_v3_bin_details.CreateFromDiscriminatorValue); } },
                { "brand", n => { Brand = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.Vault_payment_tokens_v3_card_brand>(); } },
                { "expiry", n => { Expiry = n.GetStringValue(); } },
                { "last_digits", n => { LastDigits = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "network_transaction_reference", n => { NetworkTransactionReference = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Network_transaction_reference_response>(global::Soenneker.PayPal.OpenApiClient.Models.Network_transaction_reference_response.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.Vault_payment_tokens_v3_card_type>(); } },
                { "verification", n => { Verification = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Card_verification_details>(global::Soenneker.PayPal.OpenApiClient.Models.Card_verification_details.CreateFromDiscriminatorValue); } },
                { "verification_status", n => { VerificationStatus = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.Card_verification_status>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Card_response_entity_authentication_result>("authentication_result", AuthenticationResult);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Card_response_entity_billing_address>("billing_address", BillingAddress);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Vault_payment_tokens_v3_bin_details>("bin_details", BinDetails);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.Vault_payment_tokens_v3_card_brand>("brand", Brand);
            writer.WriteStringValue("expiry", Expiry);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Network_transaction_reference_response>("network_transaction_reference", NetworkTransactionReference);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.Vault_payment_tokens_v3_card_type>("type", Type);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Card_verification_details>("verification", Verification);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.Card_verification_status>("verification_status", VerificationStatus);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
