// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.PayPal.OpenApiClient.Models.CatalogsProductsV1PatchValueMember1"/>, <see cref="global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper"/>, <see cref="global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper2"/>, <see cref="global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper3"/>, <see cref="global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper4"/>, <see cref="global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper5"/>, <see cref="global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper6"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CatalogsProductsV1PatchValue : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PayPal.OpenApiClient.Models.CatalogsProductsV1PatchValueMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.CatalogsProductsV1PatchValueMember1? CatalogsProductsV1PatchValueMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.CatalogsProductsV1PatchValueMember1 CatalogsProductsV1PatchValueMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper? PatchValueWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper PatchValueWrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper2? PatchValueWrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper2 PatchValueWrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper3? PatchValueWrapper3 { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper3 PatchValueWrapper3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper4? PatchValueWrapper4 { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper4 PatchValueWrapper4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper5? PatchValueWrapper5 { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper5 PatchValueWrapper5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper6? PatchValueWrapper6 { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper6 PatchValueWrapper6 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.CatalogsProductsV1PatchValue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.CatalogsProductsV1PatchValue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.PayPal.OpenApiClient.Models.CatalogsProductsV1PatchValue();
            result.CatalogsProductsV1PatchValueMember1 = new global::Soenneker.PayPal.OpenApiClient.Models.CatalogsProductsV1PatchValueMember1();
            result.PatchValueWrapper = new global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper();
            result.PatchValueWrapper2 = new global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper2();
            result.PatchValueWrapper3 = new global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper3();
            result.PatchValueWrapper4 = new global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper4();
            result.PatchValueWrapper5 = new global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper5();
            result.PatchValueWrapper6 = new global::Soenneker.PayPal.OpenApiClient.Models.PatchValueWrapper6();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CatalogsProductsV1PatchValueMember1 != null || PatchValueWrapper != null || PatchValueWrapper2 != null || PatchValueWrapper3 != null || PatchValueWrapper4 != null || PatchValueWrapper5 != null || PatchValueWrapper6 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CatalogsProductsV1PatchValueMember1, PatchValueWrapper, PatchValueWrapper2, PatchValueWrapper3, PatchValueWrapper4, PatchValueWrapper5, PatchValueWrapper6);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CatalogsProductsV1PatchValueMember1>(null, CatalogsProductsV1PatchValueMember1, PatchValueWrapper, PatchValueWrapper2, PatchValueWrapper3, PatchValueWrapper4, PatchValueWrapper5, PatchValueWrapper6);
        }
    }
}
#pragma warning restore CS0618
