// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// The payment card to use to fund a payment. Card can be a credit or debit card.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CheckoutOrdersV2CardResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Additional attributes associated with the use of this card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardAttributesResponse? Attributes { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardAttributesResponse Attributes { get; set; }
#endif
        /// <summary>Results of Authentication such as 3D Secure.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2AuthenticationResponse? AuthenticationResult { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2AuthenticationResponse AuthenticationResult { get; set; }
#endif
        /// <summary>Array of brands or networks associated with the card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardResponse_available_networks>? AvailableNetworks { get; private set; }
#nullable restore
#else
        public List<global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardResponse_available_networks> AvailableNetworks { get; private set; }
#endif
        /// <summary>The bin_details property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardResponse_bin_details? BinDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardResponse_bin_details BinDetails { get; set; }
#endif
        /// <summary>The card network or brand. Applies to credit, debit, gift, and payment cards.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardBrand? Brand { get; set; }
        /// <summary>The expiry property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardResponse_expiry? Expiry { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardResponse_expiry Expiry { get; set; }
#endif
        /// <summary>Representation of card details as received in the request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardFromRequest? FromRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardFromRequest FromRequest { get; set; }
#endif
        /// <summary>The last digits of the payment card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastDigits { get; private set; }
#nullable restore
#else
        public string LastDigits { get; private set; }
#endif
        /// <summary>The card holder&apos;s name as it appears on the card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Provides additional details to process a payment using a `card` that has been stored or is intended to be stored (also referred to as stored_credential or card-on-file).&lt;br/&gt;Parameter compatibility:&lt;br/&gt;&lt;ul&gt;&lt;li&gt;`payment_type=ONE_TIME` is compatible only with `payment_initiator=CUSTOMER`.&lt;/li&gt;&lt;li&gt;`usage=FIRST` is compatible only with `payment_initiator=CUSTOMER`.&lt;/li&gt;&lt;li&gt;`previous_transaction_reference` or `previous_network_transaction_reference` is compatible only with `payment_initiator=MERCHANT`.&lt;/li&gt;&lt;li&gt;Only one of the parameters - `previous_transaction_reference` and `previous_network_transaction_reference` - can be present in the request.&lt;/li&gt;&lt;/ul&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.CardStoredCredential? StoredCredential { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.CardStoredCredential StoredCredential { get; set; }
#endif
        /// <summary>Type of card. i.e Credit, Debit and so on.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardResponse"/> and sets the default values.
        /// </summary>
        public CheckoutOrdersV2CardResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attributes", n => { Attributes = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardAttributesResponse>(global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardAttributesResponse.CreateFromDiscriminatorValue); } },
                { "authentication_result", n => { AuthenticationResult = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2AuthenticationResponse>(global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2AuthenticationResponse.CreateFromDiscriminatorValue); } },
                { "available_networks", n => { AvailableNetworks = n.GetCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardResponse_available_networks>(global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardResponse_available_networks.CreateFromDiscriminatorValue)?.AsList(); } },
                { "bin_details", n => { BinDetails = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardResponse_bin_details>(global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardResponse_bin_details.CreateFromDiscriminatorValue); } },
                { "brand", n => { Brand = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardBrand>(); } },
                { "expiry", n => { Expiry = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardResponse_expiry>(global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardResponse_expiry.CreateFromDiscriminatorValue); } },
                { "from_request", n => { FromRequest = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardFromRequest>(global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardFromRequest.CreateFromDiscriminatorValue); } },
                { "last_digits", n => { LastDigits = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "stored_credential", n => { StoredCredential = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CardStoredCredential>(global::Soenneker.PayPal.OpenApiClient.Models.CardStoredCredential.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardAttributesResponse>("attributes", Attributes);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2AuthenticationResponse>("authentication_result", AuthenticationResult);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardResponse_bin_details>("bin_details", BinDetails);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardBrand>("brand", Brand);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardResponse_expiry>("expiry", Expiry);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardFromRequest>("from_request", FromRequest);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CardStoredCredential>("stored_credential", StoredCredential);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.CheckoutOrdersV2CardType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
