// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// The shipping details.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Checkout_orders_v2_shipping_detail : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>&quot;The portable international postal address. Maps to [AddressValidationMetadata](https://github.com/googlei18n/libaddressinput/wiki/AddressValidationMetadata) and HTML 5.1 [Autofilling form controls: the autocomplete attribute](https://www.w3.org/TR/html51/sec-forms.html#autofilling-form-controls-the-autocomplete-attribute).&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail_address? Address { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail_address Address { get; set; }
#endif
        /// <summary>The internationalized email address.&lt;blockquote&gt;&lt;strong&gt;Note:&lt;/strong&gt; Up to 64 characters are allowed before and 255 characters are allowed after the &lt;code&gt;@&lt;/code&gt; sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern verifies that an unquoted &lt;code&gt;@&lt;/code&gt; sign exists.&lt;/blockquote&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailAddress { get; set; }
#nullable restore
#else
        public string EmailAddress { get; set; }
#endif
        /// <summary>The name of the party.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail_name? Name { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail_name Name { get; set; }
#endif
        /// <summary>An array of shipping options that the payee or merchant offers to the payer to ship or pick up their items.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_option>? Options { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_option> Options { get; set; }
#endif
        /// <summary>The phone number, in its canonical international [E.164 numbering plan format](https://www.itu.int/rec/T-REC-E.164/en).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail_phone_number? PhoneNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail_phone_number PhoneNumber { get; set; }
#endif
        /// <summary>A classification for the method of purchase fulfillment (e.g shipping, in-store pickup, etc). Either `type` or `options` may be present, but not both.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail"/> and sets the default values.
        /// </summary>
        public Checkout_orders_v2_shipping_detail()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail_address>(global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail_address.CreateFromDiscriminatorValue); } },
                { "email_address", n => { EmailAddress = n.GetStringValue(); } },
                { "name", n => { Name = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail_name>(global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail_name.CreateFromDiscriminatorValue); } },
                { "options", n => { Options = n.GetCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_option>(global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_option.CreateFromDiscriminatorValue)?.AsList(); } },
                { "phone_number", n => { PhoneNumber = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail_phone_number>(global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail_phone_number.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail_address>("address", Address);
            writer.WriteStringValue("email_address", EmailAddress);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail_name>("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_option>("options", Options);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail_phone_number>("phone_number", PhoneNumber);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.Checkout_orders_v2_shipping_detail_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
