// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// The credit not processed details.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Credit_not_processed : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Details of Agreed Refund between customer and merchant.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Agreed_refund_details? AgreedRefundDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Agreed_refund_details AgreedRefundDetails { get; set; }
#endif
        /// <summary>The cancellation details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Cancellation_details? CancellationDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Cancellation_details CancellationDetails { get; set; }
#endif
        /// <summary>The currency and amount for a financial transaction, such as a balance or payment due.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Customer_disputes_v1_money? ExpectedRefund { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Customer_disputes_v1_money ExpectedRefund { get; set; }
#endif
        /// <summary>The issue type.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.Credit_not_processed_issue_type? IssueType { get; set; }
        /// <summary>The product information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Product_details? ProductDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Product_details ProductDetails { get; set; }
#endif
        /// <summary>The service details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Service_details? ServiceDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Service_details ServiceDetails { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Credit_not_processed"/> and sets the default values.
        /// </summary>
        public Credit_not_processed()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Credit_not_processed"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.Credit_not_processed CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.Credit_not_processed();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agreed_refund_details", n => { AgreedRefundDetails = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Agreed_refund_details>(global::Soenneker.PayPal.OpenApiClient.Models.Agreed_refund_details.CreateFromDiscriminatorValue); } },
                { "cancellation_details", n => { CancellationDetails = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Cancellation_details>(global::Soenneker.PayPal.OpenApiClient.Models.Cancellation_details.CreateFromDiscriminatorValue); } },
                { "expected_refund", n => { ExpectedRefund = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Customer_disputes_v1_money>(global::Soenneker.PayPal.OpenApiClient.Models.Customer_disputes_v1_money.CreateFromDiscriminatorValue); } },
                { "issue_type", n => { IssueType = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.Credit_not_processed_issue_type>(); } },
                { "product_details", n => { ProductDetails = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Product_details>(global::Soenneker.PayPal.OpenApiClient.Models.Product_details.CreateFromDiscriminatorValue); } },
                { "service_details", n => { ServiceDetails = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Service_details>(global::Soenneker.PayPal.OpenApiClient.Models.Service_details.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Agreed_refund_details>("agreed_refund_details", AgreedRefundDetails);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Cancellation_details>("cancellation_details", CancellationDetails);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Customer_disputes_v1_money>("expected_refund", ExpectedRefund);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.Credit_not_processed_issue_type>("issue_type", IssueType);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Product_details>("product_details", ProductDetails);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Service_details>("service_details", ServiceDetails);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
