// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>The cryptocurrency symbol or code ticker options. Assigned by liquidity providers and exchanges.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CryptocurrencySymbol
    {
        [EnumMember(Value = "BTC")]
        #pragma warning disable CS1591
        Btc,
        #pragma warning restore CS1591
        [EnumMember(Value = "ETH")]
        #pragma warning disable CS1591
        Eth,
        #pragma warning restore CS1591
        [EnumMember(Value = "BCH")]
        #pragma warning disable CS1591
        Bch,
        #pragma warning restore CS1591
        [EnumMember(Value = "LTC")]
        #pragma warning disable CS1591
        Ltc,
        #pragma warning restore CS1591
        [EnumMember(Value = "PYUSD")]
        #pragma warning disable CS1591
        Pyusd,
        #pragma warning restore CS1591
        [EnumMember(Value = "LINK")]
        #pragma warning disable CS1591
        Link,
        #pragma warning restore CS1591
        [EnumMember(Value = "SOL")]
        #pragma warning disable CS1591
        Sol,
        #pragma warning restore CS1591
        [EnumMember(Value = "MATIC")]
        #pragma warning disable CS1591
        Matic,
        #pragma warning restore CS1591
    }
}
