// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>The phone type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CustomerPartnerReferralsV2PhoneType
    {
        [EnumMember(Value = "FAX")]
        #pragma warning disable CS1591
        Fax,
        #pragma warning restore CS1591
        [EnumMember(Value = "HOME")]
        #pragma warning disable CS1591
        Home,
        #pragma warning restore CS1591
        [EnumMember(Value = "MOBILE")]
        #pragma warning disable CS1591
        Mobile,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAGER")]
        #pragma warning disable CS1591
        Pager,
        #pragma warning restore CS1591
    }
}
