// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>The role of the email address.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CustomerPartnerReferralsV2EmailType
    {
        [EnumMember(Value = "CUSTOMER_SERVICE")]
        #pragma warning disable CS1591
        CustomerService,
        #pragma warning restore CS1591
    }
}
