// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Customer_partner_referrals_v2_error_500_name
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "INTERNAL_SERVER_ERROR")]
        #pragma warning disable CS1591
        INTERNAL_SERVER_ERROR,
        #pragma warning restore CS1591
    }
}
