// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// The outcome of a dispute.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Dispute_outcome : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The currency and amount for a financial transaction, such as a balance or payment due.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Customer_disputes_v1_money? AmountRefunded { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Customer_disputes_v1_money AmountRefunded { get; set; }
#endif
        /// <summary>The details needed to represent a specific cryptocurrency balance, such as its symbol and quantity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Cryptocurrency? AssetRefunded { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Cryptocurrency AssetRefunded { get; set; }
#endif
        /// <summary>The outcome of a resolved dispute.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.Dispute_outcome_outcome_code? OutcomeCode { get; set; }
        /// <summary>The reason for the adjudication type.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.Adjudication_reason? OutcomeReason { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Dispute_outcome"/> and sets the default values.
        /// </summary>
        public Dispute_outcome()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Dispute_outcome"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.Dispute_outcome CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.Dispute_outcome();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount_refunded", n => { AmountRefunded = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Customer_disputes_v1_money>(global::Soenneker.PayPal.OpenApiClient.Models.Customer_disputes_v1_money.CreateFromDiscriminatorValue); } },
                { "asset_refunded", n => { AssetRefunded = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Cryptocurrency>(global::Soenneker.PayPal.OpenApiClient.Models.Cryptocurrency.CreateFromDiscriminatorValue); } },
                { "outcome_code", n => { OutcomeCode = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.Dispute_outcome_outcome_code>(); } },
                { "outcome_reason", n => { OutcomeReason = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.Adjudication_reason>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Customer_disputes_v1_money>("amount_refunded", AmountRefunded);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Cryptocurrency>("asset_refunded", AssetRefunded);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.Dispute_outcome_outcome_code>("outcome_code", OutcomeCode);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.Adjudication_reason>("outcome_reason", OutcomeReason);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
