// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// The dispute details.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Dispute_1 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The Teammate Adjudication details for the dispute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Adjudication_1>? Adjudications { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Adjudication_1> Adjudications { get; set; }
#endif
        /// <summary>The allowed response options for the buyer/seller update actions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.AllowedResponseOptions? AllowedResponseOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.AllowedResponseOptions AllowedResponseOptions { get; set; }
#endif
        /// <summary>The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.&lt;blockquote&gt;&lt;strong&gt;Note:&lt;/strong&gt; The regular expression provides guidance but does not reject all invalid dates.&lt;/blockquote&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BuyerResponseDueDate { get; set; }
#nullable restore
#else
        public string BuyerResponseDueDate { get; set; }
#endif
        /// <summary>The contact details that a merchant provides to the customer to use to share their evidence documents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.CommunicationDetails? CommunicationDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.CommunicationDetails CommunicationDetails { get; set; }
#endif
        /// <summary>The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.&lt;blockquote&gt;&lt;strong&gt;Note:&lt;/strong&gt; The regular expression provides guidance but does not reject all invalid dates.&lt;/blockquote&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreateTime { get; set; }
#nullable restore
#else
        public string CreateTime { get; set; }
#endif
        /// <summary>The currency and amount for a financial transaction, such as a balance or payment due.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.CustomerDisputesV1Money? DisputeAmount { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.CustomerDisputesV1Money DisputeAmount { get; set; }
#endif
        /// <summary>The details needed to represent a specific cryptocurrency balance, such as its symbol and quantity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Cryptocurrency_1? DisputeAsset { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Cryptocurrency_1 DisputeAsset { get; set; }
#endif
        /// <summary>The channel where the customer created the dispute.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.DisputeChannel? DisputeChannel { get; private set; }
        /// <summary>An array of transactions for which disputes were created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PayPal.OpenApiClient.Models.TransactionInfo>? DisputedTransactions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PayPal.OpenApiClient.Models.TransactionInfo> DisputedTransactions { get; set; }
#endif
        /// <summary>The ID of the dispute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisputeId { get; private set; }
#nullable restore
#else
        public string DisputeId { get; private set; }
#endif
        /// <summary>The stage in the dispute lifecycle.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.DisputeLifecycleStage? DisputeLifeCycleStage { get; private set; }
        /// <summary>The outcome of a dispute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.DisputeOutcome? DisputeOutcome { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.DisputeOutcome DisputeOutcome { get; set; }
#endif
        /// <summary>An array of evidence documents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Evidence_1>? Evidences { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Evidence_1> Evidences { get; set; }
#endif
        /// <summary>The extended properties for the dispute. Includes additional information for a dispute category, such as billing disputes, the original transaction ID, and the correct amount.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Extensions_1? Extensions { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Extensions_1 Extensions { get; set; }
#endif
        /// <summary>The code that identifies the reason for the credit card chargeback. Each card issuer follows their own standards for defining reason type, code, and its format. For more details about the external reason code, see the card issue site. Available for only unbranded transactions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalReasonCode { get; set; }
#nullable restore
#else
        public string ExternalReasonCode { get; set; }
#endif
        /// <summary>Policy that determines whether the fee needs to be charged, retained or returned while moving the money as part of dispute process.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Dispute_1_fee_policy? FeePolicy { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Dispute_1_fee_policy FeePolicy { get; set; }
#endif
        /// <summary>The movements of fund due to the dispute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PayPal.OpenApiClient.Models.FundMovement>? FundMovements { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PayPal.OpenApiClient.Models.FundMovement> FundMovements { get; set; }
#endif
        /// <summary>An array of request-related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links/).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PayPal.OpenApiClient.Models.CustomerDisputesV1LinkDescription>? Links { get; private set; }
#nullable restore
#else
        public List<global::Soenneker.PayPal.OpenApiClient.Models.CustomerDisputesV1LinkDescription> Links { get; private set; }
#endif
        /// <summary>An array of customer- or merchant-posted messages for the dispute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Message_1>? Messages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Message_1> Messages { get; set; }
#endif
        /// <summary>The money_movements property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MoneyMovements { get; set; }
#nullable restore
#else
        public string MoneyMovements { get; set; }
#endif
        /// <summary>The merchant-proposed offer for a dispute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Offer_1? Offer { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Offer_1 Offer { get; set; }
#endif
        /// <summary>The reason for the item-level dispute. For information about the required information for each dispute reason and associated evidence type, see &lt;a href=&quot;/docs/integration/direct/customer-disputes/integration-guide/#dispute-reasons&quot;&gt;dispute reasons&lt;/a&gt;.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.DisputeReason? Reason { get; set; }
        /// <summary>The refund details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.RefundDetails? RefundDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.RefundDetails RefundDetails { get; set; }
#endif
        /// <summary>The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.&lt;blockquote&gt;&lt;strong&gt;Note:&lt;/strong&gt; The regular expression provides guidance but does not reject all invalid dates.&lt;/blockquote&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SellerResponseDueDate { get; set; }
#nullable restore
#else
        public string SellerResponseDueDate { get; set; }
#endif
        /// <summary>The overall status of the dispute, constant for all the parties involved at anytime during the dispute lifecycle.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.Status_1? Status { get; private set; }
        /// <summary>An array of all the supporting information that are associated to this dispute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PayPal.OpenApiClient.Models.SupportingInfo>? SupportingInfo { get; private set; }
#nullable restore
#else
        public List<global::Soenneker.PayPal.OpenApiClient.Models.SupportingInfo> SupportingInfo { get; private set; }
#endif
        /// <summary>The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.&lt;blockquote&gt;&lt;strong&gt;Note:&lt;/strong&gt; The regular expression provides guidance but does not reject all invalid dates.&lt;/blockquote&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdateTime { get; set; }
#nullable restore
#else
        public string UpdateTime { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Dispute_1"/> and sets the default values.
        /// </summary>
        public Dispute_1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Dispute_1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.Dispute_1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.Dispute_1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "adjudications", n => { Adjudications = n.GetCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Adjudication_1>(global::Soenneker.PayPal.OpenApiClient.Models.Adjudication_1.CreateFromDiscriminatorValue)?.AsList(); } },
                { "allowed_response_options", n => { AllowedResponseOptions = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.AllowedResponseOptions>(global::Soenneker.PayPal.OpenApiClient.Models.AllowedResponseOptions.CreateFromDiscriminatorValue); } },
                { "buyer_response_due_date", n => { BuyerResponseDueDate = n.GetStringValue(); } },
                { "communication_details", n => { CommunicationDetails = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CommunicationDetails>(global::Soenneker.PayPal.OpenApiClient.Models.CommunicationDetails.CreateFromDiscriminatorValue); } },
                { "create_time", n => { CreateTime = n.GetStringValue(); } },
                { "dispute_amount", n => { DisputeAmount = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CustomerDisputesV1Money>(global::Soenneker.PayPal.OpenApiClient.Models.CustomerDisputesV1Money.CreateFromDiscriminatorValue); } },
                { "dispute_asset", n => { DisputeAsset = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Cryptocurrency_1>(global::Soenneker.PayPal.OpenApiClient.Models.Cryptocurrency_1.CreateFromDiscriminatorValue); } },
                { "dispute_channel", n => { DisputeChannel = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.DisputeChannel>(); } },
                { "dispute_id", n => { DisputeId = n.GetStringValue(); } },
                { "dispute_life_cycle_stage", n => { DisputeLifeCycleStage = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.DisputeLifecycleStage>(); } },
                { "dispute_outcome", n => { DisputeOutcome = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.DisputeOutcome>(global::Soenneker.PayPal.OpenApiClient.Models.DisputeOutcome.CreateFromDiscriminatorValue); } },
                { "disputed_transactions", n => { DisputedTransactions = n.GetCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.TransactionInfo>(global::Soenneker.PayPal.OpenApiClient.Models.TransactionInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "evidences", n => { Evidences = n.GetCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Evidence_1>(global::Soenneker.PayPal.OpenApiClient.Models.Evidence_1.CreateFromDiscriminatorValue)?.AsList(); } },
                { "extensions", n => { Extensions = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Extensions_1>(global::Soenneker.PayPal.OpenApiClient.Models.Extensions_1.CreateFromDiscriminatorValue); } },
                { "external_reason_code", n => { ExternalReasonCode = n.GetStringValue(); } },
                { "fee_policy", n => { FeePolicy = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Dispute_1_fee_policy>(global::Soenneker.PayPal.OpenApiClient.Models.Dispute_1_fee_policy.CreateFromDiscriminatorValue); } },
                { "fund_movements", n => { FundMovements = n.GetCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.FundMovement>(global::Soenneker.PayPal.OpenApiClient.Models.FundMovement.CreateFromDiscriminatorValue)?.AsList(); } },
                { "links", n => { Links = n.GetCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.CustomerDisputesV1LinkDescription>(global::Soenneker.PayPal.OpenApiClient.Models.CustomerDisputesV1LinkDescription.CreateFromDiscriminatorValue)?.AsList(); } },
                { "messages", n => { Messages = n.GetCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Message_1>(global::Soenneker.PayPal.OpenApiClient.Models.Message_1.CreateFromDiscriminatorValue)?.AsList(); } },
                { "money_movements", n => { MoneyMovements = n.GetStringValue(); } },
                { "offer", n => { Offer = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Offer_1>(global::Soenneker.PayPal.OpenApiClient.Models.Offer_1.CreateFromDiscriminatorValue); } },
                { "reason", n => { Reason = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.DisputeReason>(); } },
                { "refund_details", n => { RefundDetails = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.RefundDetails>(global::Soenneker.PayPal.OpenApiClient.Models.RefundDetails.CreateFromDiscriminatorValue); } },
                { "seller_response_due_date", n => { SellerResponseDueDate = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.Status_1>(); } },
                { "supporting_info", n => { SupportingInfo = n.GetCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.SupportingInfo>(global::Soenneker.PayPal.OpenApiClient.Models.SupportingInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "update_time", n => { UpdateTime = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Adjudication_1>("adjudications", Adjudications);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.AllowedResponseOptions>("allowed_response_options", AllowedResponseOptions);
            writer.WriteStringValue("buyer_response_due_date", BuyerResponseDueDate);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CommunicationDetails>("communication_details", CommunicationDetails);
            writer.WriteStringValue("create_time", CreateTime);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.CustomerDisputesV1Money>("dispute_amount", DisputeAmount);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Cryptocurrency_1>("dispute_asset", DisputeAsset);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.TransactionInfo>("disputed_transactions", DisputedTransactions);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.DisputeOutcome>("dispute_outcome", DisputeOutcome);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Evidence_1>("evidences", Evidences);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Extensions_1>("extensions", Extensions);
            writer.WriteStringValue("external_reason_code", ExternalReasonCode);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Dispute_1_fee_policy>("fee_policy", FeePolicy);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.FundMovement>("fund_movements", FundMovements);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Message_1>("messages", Messages);
            writer.WriteStringValue("money_movements", MoneyMovements);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Offer_1>("offer", Offer);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.DisputeReason>("reason", Reason);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.RefundDetails>("refund_details", RefundDetails);
            writer.WriteStringValue("seller_response_due_date", SellerResponseDueDate);
            writer.WriteStringValue("update_time", UpdateTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
