// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>The reason for the item-level dispute. For information about the required information for each dispute reason and associated evidence type, see &lt;a href=&quot;/docs/integration/direct/customer-disputes/integration-guide/#dispute-reasons&quot;&gt;dispute reasons&lt;/a&gt;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DisputeReason
    {
        [EnumMember(Value = "MERCHANDISE_OR_SERVICE_NOT_RECEIVED")]
        #pragma warning disable CS1591
        MERCHANDISE_OR_SERVICE_NOT_RECEIVED,
        #pragma warning restore CS1591
        [EnumMember(Value = "MERCHANDISE_OR_SERVICE_NOT_AS_DESCRIBED")]
        #pragma warning disable CS1591
        MERCHANDISE_OR_SERVICE_NOT_AS_DESCRIBED,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNAUTHORISED")]
        #pragma warning disable CS1591
        UNAUTHORISED,
        #pragma warning restore CS1591
        [EnumMember(Value = "CREDIT_NOT_PROCESSED")]
        #pragma warning disable CS1591
        CREDIT_NOT_PROCESSED,
        #pragma warning restore CS1591
        [EnumMember(Value = "DUPLICATE_TRANSACTION")]
        #pragma warning disable CS1591
        DUPLICATE_TRANSACTION,
        #pragma warning restore CS1591
        [EnumMember(Value = "INCORRECT_AMOUNT")]
        #pragma warning disable CS1591
        INCORRECT_AMOUNT,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYMENT_BY_OTHER_MEANS")]
        #pragma warning disable CS1591
        PAYMENT_BY_OTHER_MEANS,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANCELED_RECURRING_BILLING")]
        #pragma warning disable CS1591
        CANCELED_RECURRING_BILLING,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROBLEM_WITH_REMITTANCE")]
        #pragma warning disable CS1591
        PROBLEM_WITH_REMITTANCE,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        OTHER,
        #pragma warning restore CS1591
    }
}
