// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// The extended properties for the dispute. Includes additional information for a dispute category, such as billing disputes, the original transaction ID, and the correct amount.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Extensions : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The billing issue details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.BillingDisputesProperties? BillingDisputeProperties { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.BillingDisputesProperties BillingDisputeProperties { get; set; }
#endif
        /// <summary>The channel through which the buyer contacted the partner to file a dispute. Partners that allow buyers to create dispute from multiple channels can use this field to help identify which channel was used for each individual dispute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BuyerContactedChannel { get; set; }
#nullable restore
#else
        public string BuyerContactedChannel { get; set; }
#endif
        /// <summary>The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.&lt;blockquote&gt;&lt;strong&gt;Note:&lt;/strong&gt; The regular expression provides guidance but does not reject all invalid dates.&lt;/blockquote&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BuyerContactedTime { get; set; }
#nullable restore
#else
        public string BuyerContactedTime { get; set; }
#endif
        /// <summary>The customer-provided merchandise issue details for the dispute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.MerchandizeDisputeProperties? MerchandizeDisputeProperties { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.MerchandizeDisputeProperties MerchandizeDisputeProperties { get; set; }
#endif
        /// <summary>Indicates that the merchant was contacted.</summary>
        public bool? MerchantContacted { get; set; }
        /// <summary>The method used to contact the merchant.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.MerchantContactedMode? MerchantContactedMode { get; set; }
        /// <summary>The outcome when the customer has contacted the merchant.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.MerchantContactedOutcome? MerchantContactedOutcome { get; set; }
        /// <summary>The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.&lt;blockquote&gt;&lt;strong&gt;Note:&lt;/strong&gt; The regular expression provides guidance but does not reject all invalid dates.&lt;/blockquote&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MerchantContactedTime { get; set; }
#nullable restore
#else
        public string MerchantContactedTime { get; set; }
#endif
        /// <summary>The dispute source through which customer initiated the dispute.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.DisputeSource? ReportedSource { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Extensions"/> and sets the default values.
        /// </summary>
        public Extensions()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Extensions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.Extensions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.Extensions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billing_dispute_properties", n => { BillingDisputeProperties = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.BillingDisputesProperties>(global::Soenneker.PayPal.OpenApiClient.Models.BillingDisputesProperties.CreateFromDiscriminatorValue); } },
                { "buyer_contacted_channel", n => { BuyerContactedChannel = n.GetStringValue(); } },
                { "buyer_contacted_time", n => { BuyerContactedTime = n.GetStringValue(); } },
                { "merchandize_dispute_properties", n => { MerchandizeDisputeProperties = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.MerchandizeDisputeProperties>(global::Soenneker.PayPal.OpenApiClient.Models.MerchandizeDisputeProperties.CreateFromDiscriminatorValue); } },
                { "merchant_contacted", n => { MerchantContacted = n.GetBoolValue(); } },
                { "merchant_contacted_mode", n => { MerchantContactedMode = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.MerchantContactedMode>(); } },
                { "merchant_contacted_outcome", n => { MerchantContactedOutcome = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.MerchantContactedOutcome>(); } },
                { "merchant_contacted_time", n => { MerchantContactedTime = n.GetStringValue(); } },
                { "reported_source", n => { ReportedSource = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.DisputeSource>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.BillingDisputesProperties>("billing_dispute_properties", BillingDisputeProperties);
            writer.WriteStringValue("buyer_contacted_channel", BuyerContactedChannel);
            writer.WriteStringValue("buyer_contacted_time", BuyerContactedTime);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.MerchandizeDisputeProperties>("merchandize_dispute_properties", MerchandizeDisputeProperties);
            writer.WriteBoolValue("merchant_contacted", MerchantContacted);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.MerchantContactedMode>("merchant_contacted_mode", MerchantContactedMode);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.MerchantContactedOutcome>("merchant_contacted_outcome", MerchantContactedOutcome);
            writer.WriteStringValue("merchant_contacted_time", MerchantContactedTime);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.DisputeSource>("reported_source", ReportedSource);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
