// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>The method used to contact the merchant.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MerchantContactedMode
    {
        [EnumMember(Value = "WEBSITE")]
        #pragma warning disable CS1591
        Website,
        #pragma warning restore CS1591
        [EnumMember(Value = "PHONE")]
        #pragma warning disable CS1591
        Phone,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMAIL")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "WRITTEN")]
        #pragma warning disable CS1591
        Written,
        #pragma warning restore CS1591
        [EnumMember(Value = "IN_PERSON")]
        #pragma warning disable CS1591
        InPerson,
        #pragma warning restore CS1591
    }
}
