// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>Indicates whether the customer, merchant, or dispute arbiter posted the message.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Message_posted_by
    {
        [EnumMember(Value = "BUYER")]
        #pragma warning disable CS1591
        BUYER,
        #pragma warning restore CS1591
        [EnumMember(Value = "SELLER")]
        #pragma warning disable CS1591
        SELLER,
        #pragma warning restore CS1591
        [EnumMember(Value = "ARBITER")]
        #pragma warning disable CS1591
        ARBITER,
        #pragma warning restore CS1591
    }
}
