// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>Operating System type of the device that the buyer is using.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum NativeAppContextOsType
    {
        [EnumMember(Value = "ANDROID")]
        #pragma warning disable CS1591
        Android,
        #pragma warning restore CS1591
        [EnumMember(Value = "IOS")]
        #pragma warning disable CS1591
        Ios,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
    }
}
