// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>The type of the history event.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Offer_history_event_type
    {
        [EnumMember(Value = "PROPOSED")]
        #pragma warning disable CS1591
        PROPOSED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCEPTED")]
        #pragma warning disable CS1591
        ACCEPTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "DENIED")]
        #pragma warning disable CS1591
        DENIED,
        #pragma warning restore CS1591
    }
}
