// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// Information used to pay using P24(Przelewy24).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class P24_1 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The country_code property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.P241CountryCode? CountryCode { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.P241CountryCode CountryCode { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.P241Email? Email { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.P241Email Email { get; set; }
#endif
        /// <summary>Friendly name of the payment scheme or bank used for the payment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MethodDescription { get; set; }
#nullable restore
#else
        public string MethodDescription { get; set; }
#endif
        /// <summary>Numeric identifier of the payment scheme or bank used for the payment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MethodId { get; set; }
#nullable restore
#else
        public string MethodId { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.P241Name? Name { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.P241Name Name { get; set; }
#endif
        /// <summary>P24 generated payment description.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentDescriptor { get; set; }
#nullable restore
#else
        public string PaymentDescriptor { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.P24_1"/> and sets the default values.
        /// </summary>
        public P24_1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.P24_1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.P24_1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.P24_1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "country_code", n => { CountryCode = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.P241CountryCode>(global::Soenneker.PayPal.OpenApiClient.Models.P241CountryCode.CreateFromDiscriminatorValue); } },
                { "email", n => { Email = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.P241Email>(global::Soenneker.PayPal.OpenApiClient.Models.P241Email.CreateFromDiscriminatorValue); } },
                { "method_description", n => { MethodDescription = n.GetStringValue(); } },
                { "method_id", n => { MethodId = n.GetStringValue(); } },
                { "name", n => { Name = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.P241Name>(global::Soenneker.PayPal.OpenApiClient.Models.P241Name.CreateFromDiscriminatorValue); } },
                { "payment_descriptor", n => { PaymentDescriptor = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.P241CountryCode>("country_code", CountryCode);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.P241Email>("email", Email);
            writer.WriteStringValue("method_description", MethodDescription);
            writer.WriteStringValue("method_id", MethodId);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.P241Name>("name", Name);
            writer.WriteStringValue("payment_descriptor", PaymentDescriptor);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
