// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>The action to take on the subscription if the initial payment for the setup fails.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PaymentPreferencesSetupFeeFailureAction
    {
        [EnumMember(Value = "CONTINUE")]
        #pragma warning disable CS1591
        ContinueValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANCEL")]
        #pragma warning disable CS1591
        Cancel,
        #pragma warning restore CS1591
    }
}
