// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// The collection of payments, or transactions, for a purchase unit in an order. For example, authorized payments, captured payments, and refunds.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Payment_collection : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An array of authorized payments for a purchase unit. A purchase unit can have zero or more authorized payments.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Authorization_with_additional_data>? Authorizations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Authorization_with_additional_data> Authorizations { get; set; }
#endif
        /// <summary>An array of captured payments for a purchase unit. A purchase unit can have zero or more captured payments.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Capture>? Captures { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Capture> Captures { get; set; }
#endif
        /// <summary>An array of refunds for a purchase unit. A purchase unit can have zero or more refunds.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Refund>? Refunds { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Refund> Refunds { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Payment_collection"/> and sets the default values.
        /// </summary>
        public Payment_collection()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Payment_collection"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.Payment_collection CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.Payment_collection();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authorizations", n => { Authorizations = n.GetCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Authorization_with_additional_data>(global::Soenneker.PayPal.OpenApiClient.Models.Authorization_with_additional_data.CreateFromDiscriminatorValue)?.AsList(); } },
                { "captures", n => { Captures = n.GetCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Capture>(global::Soenneker.PayPal.OpenApiClient.Models.Capture.CreateFromDiscriminatorValue)?.AsList(); } },
                { "refunds", n => { Refunds = n.GetCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Refund>(global::Soenneker.PayPal.OpenApiClient.Models.Refund.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Authorization_with_additional_data>("authorizations", Authorizations);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Capture>("captures", Captures);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Refund>("refunds", Refunds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
