// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>The payment term. Payment can be due upon receipt, a specified date, or in a set number of days.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Payment_term_type
    {
        [EnumMember(Value = "DUE_ON_RECEIPT")]
        #pragma warning disable CS1591
        DUE_ON_RECEIPT,
        #pragma warning restore CS1591
        [EnumMember(Value = "DUE_ON_DATE_SPECIFIED")]
        #pragma warning disable CS1591
        DUE_ON_DATE_SPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "NET_10")]
        #pragma warning disable CS1591
        NET_10,
        #pragma warning restore CS1591
        [EnumMember(Value = "NET_15")]
        #pragma warning disable CS1591
        NET_15,
        #pragma warning restore CS1591
        [EnumMember(Value = "NET_30")]
        #pragma warning disable CS1591
        NET_30,
        #pragma warning restore CS1591
        [EnumMember(Value = "NET_45")]
        #pragma warning disable CS1591
        NET_45,
        #pragma warning restore CS1591
        [EnumMember(Value = "NET_60")]
        #pragma warning disable CS1591
        NET_60,
        #pragma warning restore CS1591
        [EnumMember(Value = "NET_90")]
        #pragma warning disable CS1591
        NET_90,
        #pragma warning restore CS1591
        [EnumMember(Value = "NO_DUE_DATE")]
        #pragma warning disable CS1591
        NO_DUE_DATE,
        #pragma warning restore CS1591
    }
}
