// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>The payment method.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Payment_by_other_means_payment_method
    {
        [EnumMember(Value = "CASH")]
        #pragma warning disable CS1591
        CASH,
        #pragma warning restore CS1591
        [EnumMember(Value = "CREDIT_CARD")]
        #pragma warning disable CS1591
        CREDIT_CARD,
        #pragma warning restore CS1591
        [EnumMember(Value = "CHECK")]
        #pragma warning disable CS1591
        CHECK,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYPAL")]
        #pragma warning disable CS1591
        PAYPAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEBIT_CARD")]
        #pragma warning disable CS1591
        DEBIT_CARD,
        #pragma warning restore CS1591
        [EnumMember(Value = "GIFT_CARD")]
        #pragma warning disable CS1591
        GIFT_CARD,
        #pragma warning restore CS1591
        [EnumMember(Value = "BANK_TRANSFER")]
        #pragma warning disable CS1591
        BANK_TRANSFER,
        #pragma warning restore CS1591
    }
}
