// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// The payout header that is returned in response to a payout header request. Shows details for an entire payout request.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PayoutHeader : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The payouts status.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.BatchEnum? BatchStatus { get; set; }
        /// <summary>The PayPal-generated ID for a payout.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PayoutBatchId { get; set; }
#nullable restore
#else
        public string PayoutBatchId { get; set; }
#endif
        /// <summary>The sender-provided header for a payout request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.PayoutSenderBatchHeader? SenderBatchHeader { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.PayoutSenderBatchHeader SenderBatchHeader { get; set; }
#endif
        /// <summary>The date and time when processing for the payout began, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6).</summary>
        public DateTimeOffset? TimeCreated { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.PayoutHeader"/> and sets the default values.
        /// </summary>
        public PayoutHeader()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.PayoutHeader"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.PayoutHeader CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.PayoutHeader();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "batch_status", n => { BatchStatus = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.BatchEnum>(); } },
                { "payout_batch_id", n => { PayoutBatchId = n.GetStringValue(); } },
                { "sender_batch_header", n => { SenderBatchHeader = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PayoutSenderBatchHeader>(global::Soenneker.PayPal.OpenApiClient.Models.PayoutSenderBatchHeader.CreateFromDiscriminatorValue); } },
                { "time_created", n => { TimeCreated = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.BatchEnum>("batch_status", BatchStatus);
            writer.WriteStringValue("payout_batch_id", PayoutBatchId);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PayoutSenderBatchHeader>("sender_batch_header", SenderBatchHeader);
            writer.WriteDateTimeOffsetValue("time_created", TimeCreated);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
