// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>This field indicates the status of PayPal&apos;s Checkout experience throughout the order lifecycle. The values reflect the current stage of the checkout process.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PaypalWalletResponse_experience_status
    {
        [EnumMember(Value = "NOT_STARTED")]
        #pragma warning disable CS1591
        NOT_STARTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "IN_PROGRESS")]
        #pragma warning disable CS1591
        IN_PROGRESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANCELED")]
        #pragma warning disable CS1591
        CANCELED,
        #pragma warning restore CS1591
        [EnumMember(Value = "APPROVED")]
        #pragma warning disable CS1591
        APPROVED,
        #pragma warning restore CS1591
    }
}
