// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>The type of landing page to show on the PayPal site for customer checkout.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Paypal_wallet_experience_context_landing_page
    {
        [EnumMember(Value = "LOGIN")]
        #pragma warning disable CS1591
        LOGIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "GUEST_CHECKOUT")]
        #pragma warning disable CS1591
        GUEST_CHECKOUT,
        #pragma warning restore CS1591
        [EnumMember(Value = "NO_PREFERENCE")]
        #pragma warning disable CS1591
        NO_PREFERENCE,
        #pragma warning restore CS1591
    }
}
