// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// A resource that identifies a PayPal Wallet is used for payment.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PaypalWallet : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletAddress? Address { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletAddress Address { get; set; }
#endif
        /// <summary>Additional attributes associated with the use of this PayPal Wallet.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletAttributes? Attributes { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletAttributes Attributes { get; set; }
#endif
        /// <summary>The PayPal billing agreement ID. References an approved recurring payment for goods or services.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingAgreementId { get; set; }
#nullable restore
#else
        public string BillingAgreementId { get; set; }
#endif
        /// <summary>The birth_date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletBirthDate? BirthDate { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletBirthDate BirthDate { get; set; }
#endif
        /// <summary>The email_address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletEmailAddress? EmailAddress { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletEmailAddress EmailAddress { get; set; }
#endif
        /// <summary>Customizes the payer experience during the approval process for payment with PayPal.&lt;blockquote&gt;&lt;strong&gt;Note:&lt;/strong&gt; Partners and Marketplaces might configure &lt;code&gt;brand_name&lt;/code&gt; and &lt;code&gt;shipping_preference&lt;/code&gt; during partner account setup, which overrides the request values.&lt;/blockquote&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletExperienceContext? ExperienceContext { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletExperienceContext ExperienceContext { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletName? Name { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletName Name { get; set; }
#endif
        /// <summary>The phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletPhone? Phone { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletPhone Phone { get; set; }
#endif
        /// <summary>Provides additional details to process a payment using the PayPal wallet billing agreement or a vaulted payment method that has been stored or is intended to be stored.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletStoredCredential? StoredCredential { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletStoredCredential StoredCredential { get; set; }
#endif
        /// <summary>The tax_info property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletTaxInfo? TaxInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletTaxInfo TaxInfo { get; set; }
#endif
        /// <summary>The vault_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletVaultId? VaultId { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletVaultId VaultId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.PaypalWallet"/> and sets the default values.
        /// </summary>
        public PaypalWallet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.PaypalWallet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.PaypalWallet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.PaypalWallet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletAddress>(global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletAddress.CreateFromDiscriminatorValue); } },
                { "attributes", n => { Attributes = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletAttributes>(global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletAttributes.CreateFromDiscriminatorValue); } },
                { "billing_agreement_id", n => { BillingAgreementId = n.GetStringValue(); } },
                { "birth_date", n => { BirthDate = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletBirthDate>(global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletBirthDate.CreateFromDiscriminatorValue); } },
                { "email_address", n => { EmailAddress = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletEmailAddress>(global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletEmailAddress.CreateFromDiscriminatorValue); } },
                { "experience_context", n => { ExperienceContext = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletExperienceContext>(global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletExperienceContext.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletName>(global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletName.CreateFromDiscriminatorValue); } },
                { "phone", n => { Phone = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletPhone>(global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletPhone.CreateFromDiscriminatorValue); } },
                { "stored_credential", n => { StoredCredential = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletStoredCredential>(global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletStoredCredential.CreateFromDiscriminatorValue); } },
                { "tax_info", n => { TaxInfo = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletTaxInfo>(global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletTaxInfo.CreateFromDiscriminatorValue); } },
                { "vault_id", n => { VaultId = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletVaultId>(global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletVaultId.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletAddress>("address", Address);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletAttributes>("attributes", Attributes);
            writer.WriteStringValue("billing_agreement_id", BillingAgreementId);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletBirthDate>("birth_date", BirthDate);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletEmailAddress>("email_address", EmailAddress);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletExperienceContext>("experience_context", ExperienceContext);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletName>("name", Name);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletPhone>("phone", Phone);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletStoredCredential>("stored_credential", StoredCredential);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletTaxInfo>("tax_info", TaxInfo);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.PaypalWalletVaultId>("vault_id", VaultId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
