// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>The purpose of the transaction.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PurposeEnum
    {
        [EnumMember(Value = "AWARDS")]
        #pragma warning disable CS1591
        Awards,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRIZES")]
        #pragma warning disable CS1591
        Prizes,
        #pragma warning restore CS1591
        [EnumMember(Value = "DONATIONS")]
        #pragma warning disable CS1591
        Donations,
        #pragma warning restore CS1591
        [EnumMember(Value = "GOODS")]
        #pragma warning disable CS1591
        Goods,
        #pragma warning restore CS1591
        [EnumMember(Value = "SERVICES")]
        #pragma warning disable CS1591
        Services,
        #pragma warning restore CS1591
        [EnumMember(Value = "REBATES")]
        #pragma warning disable CS1591
        Rebates,
        #pragma warning restore CS1591
        [EnumMember(Value = "CASHBACK")]
        #pragma warning disable CS1591
        Cashback,
        #pragma warning restore CS1591
        [EnumMember(Value = "DISCOUNTS")]
        #pragma warning disable CS1591
        Discounts,
        #pragma warning restore CS1591
        [EnumMember(Value = "NON_GOODS_OR_SERVICES")]
        #pragma warning disable CS1591
        NonGoodsOrServices,
        #pragma warning restore CS1591
    }
}
