// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// The billing and shipping information. Includes name, email, address, phone, and language.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Recipient_info : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The billing information of the invoice recipient. Includes name, address, email, phone, and language.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Billing_info? BillingInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Billing_info BillingInfo { get; set; }
#endif
        /// <summary>The contact information of the user. Includes name and address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Contact_name_address? ShippingInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Contact_name_address ShippingInfo { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Recipient_info"/> and sets the default values.
        /// </summary>
        public Recipient_info()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Recipient_info"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.Recipient_info CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.Recipient_info();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billing_info", n => { BillingInfo = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Billing_info>(global::Soenneker.PayPal.OpenApiClient.Models.Billing_info.CreateFromDiscriminatorValue); } },
                { "shipping_info", n => { ShippingInfo = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Contact_name_address>(global::Soenneker.PayPal.OpenApiClient.Models.Contact_name_address.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Billing_info>("billing_info", BillingInfo);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Contact_name_address>("shipping_info", ShippingInfo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
