// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// The refund details of the invoice. Includes the refund type, date, amount, and method.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Refund_detail : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The currency and amount for a financial transaction, such as a balance or payment due.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Invoicing_v2_money? Amount { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Invoicing_v2_money Amount { get; set; }
#endif
        /// <summary>The payment mode or method through which the invoicer can accept the payments.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.Invoicing_v2_payment_method? Method { get; set; }
        /// <summary>The stand-alone date, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). To represent special legal values, such as a date of birth, you should use dates with no associated time or time-zone data. Whenever possible, use the standard `date_time` type. This regular expression does not validate all dates. For example, February 31 is valid and nothing is known about leap years.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RefundDate { get; set; }
#nullable restore
#else
        public string RefundDate { get; set; }
#endif
        /// <summary>The ID for a PayPal payment transaction. Required for the `PAYPAL` payment type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RefundId { get; private set; }
#nullable restore
#else
        public string RefundId { get; private set; }
#endif
        /// <summary>The payment type. Can be PayPal or an external payment. Includes cash or a check.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.Payment_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Refund_detail"/> and sets the default values.
        /// </summary>
        public Refund_detail()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Refund_detail"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.Refund_detail CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.Refund_detail();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Invoicing_v2_money>(global::Soenneker.PayPal.OpenApiClient.Models.Invoicing_v2_money.CreateFromDiscriminatorValue); } },
                { "method", n => { Method = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.Invoicing_v2_payment_method>(); } },
                { "refund_date", n => { RefundDate = n.GetStringValue(); } },
                { "refund_id", n => { RefundId = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.Payment_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Invoicing_v2_money>("amount", Amount);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.Invoicing_v2_payment_method>("method", Method);
            writer.WriteStringValue("refund_date", RefundDate);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.Payment_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
