// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// Refunds a captured payment, by ID. For a full refund, include an empty request body. For a partial refund, include an &lt;code&gt;amount&lt;/code&gt; object in the request body.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Refund_request : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The currency and amount for a financial transaction, such as a balance or payment due.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Payments_payment_v2_money? Amount { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Payments_payment_v2_money Amount { get; set; }
#endif
        /// <summary>The API caller-provided external ID. Used to reconcile API caller-initiated transactions with PayPal transactions. Appears in transaction and settlement reports. The pattern is defined by an external party and supports Unicode.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomId { get; set; }
#nullable restore
#else
        public string CustomId { get; set; }
#endif
        /// <summary>The API caller-provided external invoice ID for this order. The pattern is defined by an external party and supports Unicode.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceId { get; set; }
#nullable restore
#else
        public string InvoiceId { get; set; }
#endif
        /// <summary>The reason for the refund. Appears in both the payer&apos;s transaction history and the emails that the payer receives. The pattern is defined by an external party and supports Unicode.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NoteToPayer { get; set; }
#nullable restore
#else
        public string NoteToPayer { get; set; }
#endif
        /// <summary>Any additional payments instructions during refund payment processing. This object is only applicable to merchants that have been enabled for PayPal Commerce Platform for Marketplaces and Platforms capability. Please speak to your account manager if you want to use this capability.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Payment_instruction_2? PaymentInstruction { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Payment_instruction_2 PaymentInstruction { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Refund_request"/> and sets the default values.
        /// </summary>
        public Refund_request()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Refund_request"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.Refund_request CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.Refund_request();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Payments_payment_v2_money>(global::Soenneker.PayPal.OpenApiClient.Models.Payments_payment_v2_money.CreateFromDiscriminatorValue); } },
                { "custom_id", n => { CustomId = n.GetStringValue(); } },
                { "invoice_id", n => { InvoiceId = n.GetStringValue(); } },
                { "note_to_payer", n => { NoteToPayer = n.GetStringValue(); } },
                { "payment_instruction", n => { PaymentInstruction = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Payment_instruction_2>(global::Soenneker.PayPal.OpenApiClient.Models.Payment_instruction_2.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Payments_payment_v2_money>("amount", Amount);
            writer.WriteStringValue("custom_id", CustomId);
            writer.WriteStringValue("invoice_id", InvoiceId);
            writer.WriteStringValue("note_to_payer", NoteToPayer);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Payment_instruction_2>("payment_instruction", PaymentInstruction);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
