// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// The return details for the product.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReturnDetails : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The method that the customer used to return the product.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.ReturnDetails_mode? Mode { get; set; }
        /// <summary>Indicates whether customer has the return receipt.</summary>
        public bool? Receipt { get; set; }
        /// <summary>The confirmation number for the item return.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReturnConfirmationNumber { get; set; }
#nullable restore
#else
        public string ReturnConfirmationNumber { get; set; }
#endif
        /// <summary>If `true`, indicates that the item was returned but the seller refused to accept the return and if `false`, indicates the item was not attempted to return.</summary>
        public bool? Returned { get; set; }
        /// <summary>The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.&lt;blockquote&gt;&lt;strong&gt;Note:&lt;/strong&gt; The regular expression provides guidance but does not reject all invalid dates.&lt;/blockquote&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReturnTime { get; set; }
#nullable restore
#else
        public string ReturnTime { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.ReturnDetails"/> and sets the default values.
        /// </summary>
        public ReturnDetails()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.ReturnDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.ReturnDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.ReturnDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "mode", n => { Mode = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.ReturnDetails_mode>(); } },
                { "receipt", n => { Receipt = n.GetBoolValue(); } },
                { "return_confirmation_number", n => { ReturnConfirmationNumber = n.GetStringValue(); } },
                { "return_time", n => { ReturnTime = n.GetStringValue(); } },
                { "returned", n => { Returned = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.ReturnDetails_mode>("mode", Mode);
            writer.WriteBoolValue("receipt", Receipt);
            writer.WriteStringValue("return_confirmation_number", ReturnConfirmationNumber);
            writer.WriteBoolValue("returned", Returned);
            writer.WriteStringValue("return_time", ReturnTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
