// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// The invoice search parameters.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Search_data : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Indicates whether to list merchant-archived invoices in the response. Value is:&lt;ul&gt;&lt;li&gt;&lt;code&gt;true&lt;/code&gt;. Response lists only merchant-archived invoices.&lt;/li&gt;&lt;li&gt;&lt;code&gt;false&lt;/code&gt;. Response lists only unarchived invoices.&lt;/li&gt;&lt;li&gt;&lt;code&gt;null&lt;/code&gt;. Response lists all invoices.&lt;/li&gt;&lt;/ul&gt;</summary>
        public bool? Archived { get; set; }
        /// <summary>The date and time range. Filters invoices by creation date, invoice date, due date, and payment date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Date_time_range? CreationDateRange { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Date_time_range CreationDateRange { get; set; }
#endif
        /// <summary>The [three-character ISO-4217 currency code](/api/rest/reference/currency-codes/) that identifies the currency.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyCode { get; set; }
#nullable restore
#else
        public string CurrencyCode { get; set; }
#endif
        /// <summary>The date range. Filters invoices by creation date, invoice date, due date, and payment date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Date_range? DueDateRange { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Date_range DueDateRange { get; set; }
#endif
        /// <summary>A CSV file of fields to return for the user, if available. Because the invoice object can be very large, field filtering is required. Valid collection fields are &lt;code&gt;items&lt;/code&gt;, &lt;code&gt;payments&lt;/code&gt;, &lt;code&gt;refunds&lt;/code&gt;, &lt;code&gt;additional_recipients_info&lt;/code&gt;, and &lt;code&gt;attachments&lt;/code&gt;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Fields { get; set; }
#nullable restore
#else
        public List<string> Fields { get; set; }
#endif
        /// <summary>The date range. Filters invoices by creation date, invoice date, due date, and payment date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Date_range? InvoiceDateRange { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Date_range InvoiceDateRange { get; set; }
#endif
        /// <summary>Filters the search by the invoice number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceNumber { get; set; }
#nullable restore
#else
        public string InvoiceNumber { get; set; }
#endif
        /// <summary>A private bookkeeping memo for the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Memo { get; set; }
#nullable restore
#else
        public string Memo { get; set; }
#endif
        /// <summary>The date and time range. Filters invoices by creation date, invoice date, due date, and payment date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Date_time_range? PaymentDateRange { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Date_time_range PaymentDateRange { get; set; }
#endif
        /// <summary>Filters the search by the recipient business name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecipientBusinessName { get; set; }
#nullable restore
#else
        public string RecipientBusinessName { get; set; }
#endif
        /// <summary>Filters the search by the email address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecipientEmail { get; set; }
#nullable restore
#else
        public string RecipientEmail { get; set; }
#endif
        /// <summary>Filters the search by the recipient first name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecipientFirstName { get; set; }
#nullable restore
#else
        public string RecipientFirstName { get; set; }
#endif
        /// <summary>Filters the search by the recipient last name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecipientLastName { get; set; }
#nullable restore
#else
        public string RecipientLastName { get; set; }
#endif
        /// <summary>The reference data. Includes a Purchase Order (PO) number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reference { get; set; }
#nullable restore
#else
        public string Reference { get; set; }
#endif
        /// <summary>An array of status values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Invoice_status?>? Status { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Invoice_status?> Status { get; set; }
#endif
        /// <summary>The amount range.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Amount_range? TotalAmountRange { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Amount_range TotalAmountRange { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Search_data"/> and sets the default values.
        /// </summary>
        public Search_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Search_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.Search_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.Search_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "archived", n => { Archived = n.GetBoolValue(); } },
                { "creation_date_range", n => { CreationDateRange = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Date_time_range>(global::Soenneker.PayPal.OpenApiClient.Models.Date_time_range.CreateFromDiscriminatorValue); } },
                { "currency_code", n => { CurrencyCode = n.GetStringValue(); } },
                { "due_date_range", n => { DueDateRange = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Date_range>(global::Soenneker.PayPal.OpenApiClient.Models.Date_range.CreateFromDiscriminatorValue); } },
                { "fields", n => { Fields = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "invoice_date_range", n => { InvoiceDateRange = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Date_range>(global::Soenneker.PayPal.OpenApiClient.Models.Date_range.CreateFromDiscriminatorValue); } },
                { "invoice_number", n => { InvoiceNumber = n.GetStringValue(); } },
                { "memo", n => { Memo = n.GetStringValue(); } },
                { "payment_date_range", n => { PaymentDateRange = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Date_time_range>(global::Soenneker.PayPal.OpenApiClient.Models.Date_time_range.CreateFromDiscriminatorValue); } },
                { "recipient_business_name", n => { RecipientBusinessName = n.GetStringValue(); } },
                { "recipient_email", n => { RecipientEmail = n.GetStringValue(); } },
                { "recipient_first_name", n => { RecipientFirstName = n.GetStringValue(); } },
                { "recipient_last_name", n => { RecipientLastName = n.GetStringValue(); } },
                { "reference", n => { Reference = n.GetStringValue(); } },
                { "status", n => { Status = n.GetCollectionOfEnumValues<global::Soenneker.PayPal.OpenApiClient.Models.Invoice_status>()?.AsList(); } },
                { "total_amount_range", n => { TotalAmountRange = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Amount_range>(global::Soenneker.PayPal.OpenApiClient.Models.Amount_range.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("archived", Archived);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Date_time_range>("creation_date_range", CreationDateRange);
            writer.WriteStringValue("currency_code", CurrencyCode);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Date_range>("due_date_range", DueDateRange);
            writer.WriteCollectionOfPrimitiveValues<string>("fields", Fields);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Date_range>("invoice_date_range", InvoiceDateRange);
            writer.WriteStringValue("invoice_number", InvoiceNumber);
            writer.WriteStringValue("memo", Memo);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Date_time_range>("payment_date_range", PaymentDateRange);
            writer.WriteStringValue("recipient_business_name", RecipientBusinessName);
            writer.WriteStringValue("recipient_email", RecipientEmail);
            writer.WriteStringValue("recipient_first_name", RecipientFirstName);
            writer.WriteStringValue("recipient_last_name", RecipientLastName);
            writer.WriteStringValue("reference", Reference);
            writer.WriteCollectionOfEnumValues<global::Soenneker.PayPal.OpenApiClient.Models.Invoice_status>("status", Status);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Amount_range>("total_amount_range", TotalAmountRange);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
