// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>The status of the subscription.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubscriptionStatusEnum
    {
        [EnumMember(Value = "APPROVAL_PENDING")]
        #pragma warning disable CS1591
        ApprovalPending,
        #pragma warning restore CS1591
        [EnumMember(Value = "APPROVED")]
        #pragma warning disable CS1591
        Approved,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACTIVE")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUSPENDED")]
        #pragma warning disable CS1591
        Suspended,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANCELLED")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPIRED")]
        #pragma warning disable CS1591
        Expired,
        #pragma warning restore CS1591
    }
}
