// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>The tokenization method that generated the ID.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TokenIdRequest_type
    {
        [EnumMember(Value = "SETUP_TOKEN")]
        #pragma warning disable CS1591
        SETUP_TOKEN,
        #pragma warning restore CS1591
    }
}
