// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>The status of the item shipment. For allowed values, see &lt;a href=&quot;/docs/tracking/reference/shipping-status/&quot;&gt;Shipping Statuses&lt;/a&gt;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Tracking_status
    {
        [EnumMember(Value = "CANCELLED")]
        #pragma warning disable CS1591
        CANCELLED,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELIVERED")]
        #pragma warning disable CS1591
        DELIVERED,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOCAL_PICKUP")]
        #pragma warning disable CS1591
        LOCAL_PICKUP,
        #pragma warning restore CS1591
        [EnumMember(Value = "ON_HOLD")]
        #pragma warning disable CS1591
        ON_HOLD,
        #pragma warning restore CS1591
        [EnumMember(Value = "SHIPPED")]
        #pragma warning disable CS1591
        SHIPPED,
        #pragma warning restore CS1591
        [EnumMember(Value = "SHIPMENT_CREATED")]
        #pragma warning disable CS1591
        SHIPMENT_CREATED,
        #pragma warning restore CS1591
        [EnumMember(Value = "DROPPED_OFF")]
        #pragma warning disable CS1591
        DROPPED_OFF,
        #pragma warning restore CS1591
        [EnumMember(Value = "IN_TRANSIT")]
        #pragma warning disable CS1591
        IN_TRANSIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "RETURNED")]
        #pragma warning disable CS1591
        RETURNED,
        #pragma warning restore CS1591
        [EnumMember(Value = "LABEL_PRINTED")]
        #pragma warning disable CS1591
        LABEL_PRINTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        ERROR,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNCONFIRMED")]
        #pragma warning disable CS1591
        UNCONFIRMED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PICKUP_FAILED")]
        #pragma warning disable CS1591
        PICKUP_FAILED,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELIVERY_DELAYED")]
        #pragma warning disable CS1591
        DELIVERY_DELAYED,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELIVERY_SCHEDULED")]
        #pragma warning disable CS1591
        DELIVERY_SCHEDULED,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELIVERY_FAILED")]
        #pragma warning disable CS1591
        DELIVERY_FAILED,
        #pragma warning restore CS1591
        [EnumMember(Value = "INRETURN")]
        #pragma warning disable CS1591
        INRETURN,
        #pragma warning restore CS1591
        [EnumMember(Value = "IN_PROCESS")]
        #pragma warning disable CS1591
        IN_PROCESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEW")]
        #pragma warning disable CS1591
        NEW,
        #pragma warning restore CS1591
        [EnumMember(Value = "VOID")]
        #pragma warning disable CS1591
        VOID,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROCESSED")]
        #pragma warning disable CS1591
        PROCESSED,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_SHIPPED")]
        #pragma warning disable CS1591
        NOT_SHIPPED,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPLETED")]
        #pragma warning disable CS1591
        COMPLETED,
        #pragma warning restore CS1591
    }
}
