// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// The schema that describes the link target.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Tracker_links_targetSchema : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Any additional items.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_additionalItems? AdditionalItems { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_additionalItems AdditionalItems { get; set; }
#endif
        /// <summary>An array of sub-schemas. The data must validate against all sub-schemas.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_allOf>? AllOf { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_allOf> AllOf { get; set; }
#endif
        /// <summary>An array of sub-schemas. The data must validate against one or more sub-schemas.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_anyOf>? AnyOf { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_anyOf> AnyOf { get; set; }
#endif
        /// <summary>Definitions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_definitions? Definitions { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_definitions Definitions { get; set; }
#endif
        /// <summary>Any Dependencies.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_dependencies? Dependencies { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_dependencies Dependencies { get; set; }
#endif
        /// <summary>The fragment resolution.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FragmentResolution { get; set; }
#nullable restore
#else
        public string FragmentResolution { get; set; }
#endif
        /// <summary>An item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_items? Items { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_items Items { get; set; }
#endif
        /// <summary>An array of links.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_links>? Links { get; private set; }
#nullable restore
#else
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_links> Links { get; private set; }
#endif
        /// <summary>The media type and context-encoding scheme.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.LinkSchema2Media? Media { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.LinkSchema2Media Media { get; set; }
#endif
        /// <summary>Not.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_not? Not { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_not Not { get; set; }
#endif
        /// <summary>An array of sub-schemas. The data must validate against one sub-schema.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_oneOf>? OneOf { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_oneOf> OneOf { get; set; }
#endif
        /// <summary>To apply this schema to the instances&apos; URIs, start the URIs with this value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PathStart { get; set; }
#nullable restore
#else
        public string PathStart { get; set; }
#endif
        /// <summary>The pattern properties.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_patternProperties? PatternProperties { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_patternProperties PatternProperties { get; set; }
#endif
        /// <summary>Properties.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_properties? Properties { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_properties Properties { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema"/> and sets the default values.
        /// </summary>
        public Tracker_links_targetSchema()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "additionalItems", n => { AdditionalItems = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_additionalItems>(global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_additionalItems.CreateFromDiscriminatorValue); } },
                { "allOf", n => { AllOf = n.GetCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_allOf>(global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_allOf.CreateFromDiscriminatorValue)?.AsList(); } },
                { "anyOf", n => { AnyOf = n.GetCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_anyOf>(global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_anyOf.CreateFromDiscriminatorValue)?.AsList(); } },
                { "definitions", n => { Definitions = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_definitions>(global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_definitions.CreateFromDiscriminatorValue); } },
                { "dependencies", n => { Dependencies = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_dependencies>(global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_dependencies.CreateFromDiscriminatorValue); } },
                { "fragmentResolution", n => { FragmentResolution = n.GetStringValue(); } },
                { "items", n => { Items = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_items>(global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_items.CreateFromDiscriminatorValue); } },
                { "links", n => { Links = n.GetCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_links>(global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_links.CreateFromDiscriminatorValue)?.AsList(); } },
                { "media", n => { Media = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.LinkSchema2Media>(global::Soenneker.PayPal.OpenApiClient.Models.LinkSchema2Media.CreateFromDiscriminatorValue); } },
                { "not", n => { Not = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_not>(global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_not.CreateFromDiscriminatorValue); } },
                { "oneOf", n => { OneOf = n.GetCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_oneOf>(global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_oneOf.CreateFromDiscriminatorValue)?.AsList(); } },
                { "pathStart", n => { PathStart = n.GetStringValue(); } },
                { "patternProperties", n => { PatternProperties = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_patternProperties>(global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_patternProperties.CreateFromDiscriminatorValue); } },
                { "properties", n => { Properties = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_properties>(global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_properties.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_additionalItems>("additionalItems", AdditionalItems);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_allOf>("allOf", AllOf);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_anyOf>("anyOf", AnyOf);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_definitions>("definitions", Definitions);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_dependencies>("dependencies", Dependencies);
            writer.WriteStringValue("fragmentResolution", FragmentResolution);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_items>("items", Items);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.LinkSchema2Media>("media", Media);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_not>("not", Not);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_oneOf>("oneOf", OneOf);
            writer.WriteStringValue("pathStart", PathStart);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_patternProperties>("patternProperties", PatternProperties);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.Tracker_links_targetSchema_properties>("properties", Properties);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
