// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>The customer type associated with the Venmo payment token. This is to indicate whether the customer acting on the merchant / platform is either a business or a consumer.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VaultVenmoWalletBase_customer_type
    {
        [EnumMember(Value = "CONSUMER")]
        #pragma warning disable CS1591
        CONSUMER,
        #pragma warning restore CS1591
        [EnumMember(Value = "BUSINESS")]
        #pragma warning disable CS1591
        BUSINESS,
        #pragma warning restore CS1591
    }
}
