// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>The tenure type of the billing cycle identifies if the billing cycle is a trial(free or discounted) or regular billing cycle.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Vault_payment_tokens_v3_billing_cycle_tenure_type
    {
        [EnumMember(Value = "REGULAR")]
        #pragma warning disable CS1591
        REGULAR,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRIAL")]
        #pragma warning disable CS1591
        TRIAL,
        #pragma warning restore CS1591
    }
}
