// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>Expected business/pricing model for the billing agreement.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VaultVenmoWalletBaseUsagePattern
    {
        [EnumMember(Value = "IMMEDIATE")]
        #pragma warning disable CS1591
        Immediate,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEFERRED")]
        #pragma warning disable CS1591
        Deferred,
        #pragma warning restore CS1591
        [EnumMember(Value = "RECURRING_PREPAID")]
        #pragma warning disable CS1591
        RecurringPrepaid,
        #pragma warning restore CS1591
        [EnumMember(Value = "RECURRING_POSTPAID")]
        #pragma warning disable CS1591
        RecurringPostpaid,
        #pragma warning restore CS1591
        [EnumMember(Value = "THRESHOLD_PREPAID")]
        #pragma warning disable CS1591
        ThresholdPrepaid,
        #pragma warning restore CS1591
        [EnumMember(Value = "THRESHOLD_POSTPAID")]
        #pragma warning disable CS1591
        ThresholdPostpaid,
        #pragma warning restore CS1591
    }
}
