// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class VenmoResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>&quot;The portable international postal address. Maps to [AddressValidationMetadata](https://github.com/googlei18n/libaddressinput/wiki/AddressValidationMetadata) and HTML 5.1 [Autofilling form controls: the autocomplete attribute](https://www.w3.org/TR/html51/sec-forms.html#autofilling-form-controls-the-autocomplete-attribute).&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse_address? Address { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse_address Address { get; set; }
#endif
        /// <summary>The customer type associated with a digital wallet payment token. This is to indicate whether the customer acting on the merchant / platform is either a business or a consumer.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse_customer_type? CustomerType { get; set; }
        /// <summary>&quot;The description displayed to the consumer on the approval flow for a digital wallet, as well as on the merchant view of the payment token management experience. exp: PayPal.com.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The internationalized email address.&lt;blockquote&gt;&lt;strong&gt;Note:&lt;/strong&gt; Up to 64 characters are allowed before and 255 characters are allowed after the &lt;code&gt;@&lt;/code&gt; sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern verifies that an unquoted &lt;code&gt;@&lt;/code&gt; sign exists.&lt;/blockquote&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailAddress { get; set; }
#nullable restore
#else
        public string EmailAddress { get; set; }
#endif
        /// <summary>The name of the party.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse_name? Name { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse_name Name { get; set; }
#endif
        /// <summary>The account identifier for a PayPal account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PayerId { get; set; }
#nullable restore
#else
        public string PayerId { get; set; }
#endif
        /// <summary>Create multiple payment tokens for the same payer, merchant/platform combination. Use this when the customer has not logged in at merchant/platform. The payment token thus generated, can then also be used to create the customer account at merchant/platform. Use this also when multiple payment tokens are required for the same payer, different customer at merchant/platform. This helps to identify customers distinctly even though they may share the same PayPal account. This only applies to PayPal payment source.</summary>
        public bool? PermitMultiplePaymentTokens { get; set; }
        /// <summary>The phone information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.VaultPaymentTokensV3PhoneWithType? Phone { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.VaultPaymentTokensV3PhoneWithType Phone { get; set; }
#endif
        /// <summary>The shipping details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.WalletBaseShipping? Shipping { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.WalletBaseShipping Shipping { get; set; }
#endif
        /// <summary>Expected business/charge model for the billing agreement.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse_usage_pattern? UsagePattern { get; set; }
        /// <summary>The usage type associated with a digital wallet payment token.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse_usage_type? UsageType { get; set; }
        /// <summary>The Venmo username, as chosen by the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserName { get; set; }
#nullable restore
#else
        public string UserName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse"/> and sets the default values.
        /// </summary>
        public VenmoResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse_address>(global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse_address.CreateFromDiscriminatorValue); } },
                { "customer_type", n => { CustomerType = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse_customer_type>(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "email_address", n => { EmailAddress = n.GetStringValue(); } },
                { "name", n => { Name = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse_name>(global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse_name.CreateFromDiscriminatorValue); } },
                { "payer_id", n => { PayerId = n.GetStringValue(); } },
                { "permit_multiple_payment_tokens", n => { PermitMultiplePaymentTokens = n.GetBoolValue(); } },
                { "phone", n => { Phone = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VaultPaymentTokensV3PhoneWithType>(global::Soenneker.PayPal.OpenApiClient.Models.VaultPaymentTokensV3PhoneWithType.CreateFromDiscriminatorValue); } },
                { "shipping", n => { Shipping = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.WalletBaseShipping>(global::Soenneker.PayPal.OpenApiClient.Models.WalletBaseShipping.CreateFromDiscriminatorValue); } },
                { "usage_pattern", n => { UsagePattern = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse_usage_pattern>(); } },
                { "usage_type", n => { UsageType = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse_usage_type>(); } },
                { "user_name", n => { UserName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse_address>("address", Address);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse_customer_type>("customer_type", CustomerType);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("email_address", EmailAddress);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse_name>("name", Name);
            writer.WriteStringValue("payer_id", PayerId);
            writer.WriteBoolValue("permit_multiple_payment_tokens", PermitMultiplePaymentTokens);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VaultPaymentTokensV3PhoneWithType>("phone", Phone);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.WalletBaseShipping>("shipping", Shipping);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse_usage_pattern>("usage_pattern", UsagePattern);
            writer.WriteEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoResponse_usage_type>("usage_type", UsageType);
            writer.WriteStringValue("user_name", UserName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
