// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>
    /// Venmo wallet response.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VenmoWalletResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>The account_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseAccountId? AccountId { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseAccountId AccountId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseAddress? Address { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseAddress Address { get; set; }
#endif
        /// <summary>Additional attributes associated with the use of a Venmo Wallet.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletAttributesResponse? Attributes { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletAttributesResponse Attributes { get; set; }
#endif
        /// <summary>The email_address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseEmailAddress? EmailAddress { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseEmailAddress EmailAddress { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseName? Name { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseName Name { get; set; }
#endif
        /// <summary>The phone_number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponsePhoneNumber? PhoneNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponsePhoneNumber PhoneNumber { get; set; }
#endif
        /// <summary>Merchant preference on how the buyer can navigate back to merchant website post approving the transaction on the Venmo App.</summary>
        public global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponse_return_flow? ReturnFlow { get; private set; }
        /// <summary>The Venmo user name chosen by the user, also know as a Venmo handle.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserName { get; set; }
#nullable restore
#else
        public string UserName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponse"/> and sets the default values.
        /// </summary>
        public VenmoWalletResponse()
        {
            AdditionalData = new Dictionary<string, object>();
            ReturnFlow = global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponse_return_flow.AUTO;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_id", n => { AccountId = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseAccountId>(global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseAccountId.CreateFromDiscriminatorValue); } },
                { "address", n => { Address = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseAddress>(global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseAddress.CreateFromDiscriminatorValue); } },
                { "attributes", n => { Attributes = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletAttributesResponse>(global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletAttributesResponse.CreateFromDiscriminatorValue); } },
                { "email_address", n => { EmailAddress = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseEmailAddress>(global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseEmailAddress.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseName>(global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseName.CreateFromDiscriminatorValue); } },
                { "phone_number", n => { PhoneNumber = n.GetObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponsePhoneNumber>(global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponsePhoneNumber.CreateFromDiscriminatorValue); } },
                { "return_flow", n => { ReturnFlow = n.GetEnumValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponse_return_flow>(); } },
                { "user_name", n => { UserName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseAccountId>("account_id", AccountId);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseAddress>("address", Address);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletAttributesResponse>("attributes", Attributes);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseEmailAddress>("email_address", EmailAddress);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponseName>("name", Name);
            writer.WriteObjectValue<global::Soenneker.PayPal.OpenApiClient.Models.VenmoWalletResponsePhoneNumber>("phone_number", PhoneNumber);
            writer.WriteStringValue("user_name", UserName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
