// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>The location from which the shipping address is derived.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VenmoWalletExperienceContext_shipping_preference
    {
        [EnumMember(Value = "GET_FROM_FILE")]
        #pragma warning disable CS1591
        GET_FROM_FILE,
        #pragma warning restore CS1591
        [EnumMember(Value = "NO_SHIPPING")]
        #pragma warning disable CS1591
        NO_SHIPPING,
        #pragma warning restore CS1591
        [EnumMember(Value = "SET_PROVIDED_ADDRESS")]
        #pragma warning disable CS1591
        SET_PROVIDED_ADDRESS,
        #pragma warning restore CS1591
    }
}
