// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PayPal.OpenApiClient.Models
{
    /// <summary>A classification for the method of purchase fulfillment (e.g shipping, in-store pickup, etc). Either `type` or `options` may be present, but not both.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WalletBaseShippingType
    {
        [EnumMember(Value = "SHIPPING")]
        #pragma warning disable CS1591
        Shipping,
        #pragma warning restore CS1591
        [EnumMember(Value = "PICKUP_IN_PERSON")]
        #pragma warning disable CS1591
        PickupInPerson,
        #pragma warning restore CS1591
        [EnumMember(Value = "PICKUP_IN_STORE")]
        #pragma warning disable CS1591
        PickupInStore,
        #pragma warning restore CS1591
        [EnumMember(Value = "PICKUP_FROM_PERSON")]
        #pragma warning disable CS1591
        PickupFromPerson,
        #pragma warning restore CS1591
    }
}
