// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.PayPal.OpenApiClient.Customer_partner_referrals_v2.V2.Customer.PartnerReferrals;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.PayPal.OpenApiClient.Customer_partner_referrals_v2.V2.Customer
{
    /// <summary>
    /// Builds and executes requests for operations under \customer_partner_referrals_v2\v2\customer
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CustomerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The partnerReferrals property</summary>
        public global::Soenneker.PayPal.OpenApiClient.Customer_partner_referrals_v2.V2.Customer.PartnerReferrals.PartnerReferralsRequestBuilder PartnerReferrals
        {
            get => new global::Soenneker.PayPal.OpenApiClient.Customer_partner_referrals_v2.V2.Customer.PartnerReferrals.PartnerReferralsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Customer_partner_referrals_v2.V2.Customer.CustomerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CustomerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/customer_partner_referrals_v2/v2/customer", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Customer_partner_referrals_v2.V2.Customer.CustomerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CustomerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/customer_partner_referrals_v2/v2/customer", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
