// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.PayPal.OpenApiClient.Catalogs_products_v1.V1.Catalogs.Products.Item;
using Soenneker.PayPal.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.PayPal.OpenApiClient.Catalogs_products_v1.V1.Catalogs.Products
{
    /// <summary>
    /// Builds and executes requests for operations under \catalogs_products_v1\v1\catalogs\products
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProductsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.PayPal.OpenApiClient.catalogs_products_v1.v1.catalogs.products.item collection</summary>
        /// <param name="position">The product ID.</param>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Catalogs_products_v1.V1.Catalogs.Products.Item.WithProduct_ItemRequestBuilder"/></returns>
        public global::Soenneker.PayPal.OpenApiClient.Catalogs_products_v1.V1.Catalogs.Products.Item.WithProduct_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("product_id", position);
                return new global::Soenneker.PayPal.OpenApiClient.Catalogs_products_v1.V1.Catalogs.Products.Item.WithProduct_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Catalogs_products_v1.V1.Catalogs.Products.ProductsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalogs_products_v1/v1/catalogs/products{?page*,page_size*,total_required*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PayPal.OpenApiClient.Catalogs_products_v1.V1.Catalogs.Products.ProductsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalogs_products_v1/v1/catalogs/products{?page*,page_size*,total_required*}", rawUrl)
        {
        }
        /// <summary>
        /// Lists products.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Product_collection"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.PayPal.OpenApiClient.Models.Catalogs_products_v1_products_list_400">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.PayPal.OpenApiClient.Models.Catalogs_products_v1_products_list_401">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.PayPal.OpenApiClient.Models.Catalogs_products_v1_products_list_403">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.PayPal.OpenApiClient.Models.Catalogs_products_v1_error_500">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.PayPal.OpenApiClient.Models.Product_collection?> GetAsync(Action<RequestConfiguration<global::Soenneker.PayPal.OpenApiClient.Catalogs_products_v1.V1.Catalogs.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.PayPal.OpenApiClient.Models.Product_collection> GetAsync(Action<RequestConfiguration<global::Soenneker.PayPal.OpenApiClient.Catalogs_products_v1.V1.Catalogs.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.PayPal.OpenApiClient.Models.Catalogs_products_v1_products_list_400.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.PayPal.OpenApiClient.Models.Catalogs_products_v1_products_list_401.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.PayPal.OpenApiClient.Models.Catalogs_products_v1_products_list_403.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.PayPal.OpenApiClient.Models.Catalogs_products_v1_error_500.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.PayPal.OpenApiClient.Models.Product_collection>(requestInfo, global::Soenneker.PayPal.OpenApiClient.Models.Product_collection.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a product.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Models.Product"/></returns>
        /// <param name="body">The create product request details.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.PayPal.OpenApiClient.Models.Catalogs_products_v1_products_create_400">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.PayPal.OpenApiClient.Models.Catalogs_products_v1_products_create_401">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.PayPal.OpenApiClient.Models.Catalogs_products_v1_products_create_403">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.PayPal.OpenApiClient.Models.Catalogs_products_v1_products_create_422">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.PayPal.OpenApiClient.Models.Catalogs_products_v1_error_500">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.PayPal.OpenApiClient.Models.Product?> PostAsync(global::Soenneker.PayPal.OpenApiClient.Models.Product_request_POST body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.PayPal.OpenApiClient.Models.Product> PostAsync(global::Soenneker.PayPal.OpenApiClient.Models.Product_request_POST body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.PayPal.OpenApiClient.Models.Catalogs_products_v1_products_create_400.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.PayPal.OpenApiClient.Models.Catalogs_products_v1_products_create_401.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.PayPal.OpenApiClient.Models.Catalogs_products_v1_products_create_403.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.PayPal.OpenApiClient.Models.Catalogs_products_v1_products_create_422.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.PayPal.OpenApiClient.Models.Catalogs_products_v1_error_500.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.PayPal.OpenApiClient.Models.Product>(requestInfo, global::Soenneker.PayPal.OpenApiClient.Models.Product.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Lists products.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.PayPal.OpenApiClient.Catalogs_products_v1.V1.Catalogs.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.PayPal.OpenApiClient.Catalogs_products_v1.V1.Catalogs.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a product.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The create product request details.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.PayPal.OpenApiClient.Models.Product_request_POST body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.PayPal.OpenApiClient.Models.Product_request_POST body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PayPal.OpenApiClient.Catalogs_products_v1.V1.Catalogs.Products.ProductsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.PayPal.OpenApiClient.Catalogs_products_v1.V1.Catalogs.Products.ProductsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.PayPal.OpenApiClient.Catalogs_products_v1.V1.Catalogs.Products.ProductsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Lists products.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductsRequestBuilderGetQueryParameters 
        {
            /// <summary>A non-zero integer which is the start index of the entire list of items that are returned in the response. So, the combination of `page=1` and `page_size=20` returns the first 20 items. The combination of `page=2` and `page_size=20` returns the next 20 items.</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>The number of items to return in the response.</summary>
            [QueryParameter("page_size")]
            public int? PageSize { get; set; }
            /// <summary>Indicates whether to show the total items and total pages in the response.</summary>
            [QueryParameter("total_required")]
            public bool? TotalRequired { get; set; }
        }
    }
}
#pragma warning restore CS0618
